### ISSUE TITLE
Ability to select folders for Gallery art source

### ISSUE THREAD

**Issue by ianhanniballake** [romannurik/muzei#115]
Instead of selecting pictures one or multiple at a time, allow adding entire directories to the Gallery art source. Include all pictures in the directory, including when new pictures are added to the directory.

**Comment by callumgare** [comment]
Yes! Please! I've got a folder of phone wallpapers and not only would I like to not have to select every single individual image in it but I would also like to be able to just add new images to the folder and have them show up in the rotation without having to deliberately select the new images in Muzei.
I already love Muzei forever but nevertheless such a feature would make it even better :3

**Comment by mieleur** [comment]
This is a basic feature that Muzei should have. I have, like callumgare, a folder where I put all my favourite phone wallpapers and would like Muzei to be able to get the new pictures from there. I really hope they make this possible.

**Comment by ianhanniballake** [comment]
Added in #258 - woohoo!
