### ISSUE TITLE
Add date option to watch face

### ISSUE THREAD

**Issue by ianhanniballake** [romannurik/muzei#121]
Add support for showing the date on the Android Wear watch face

**Comment by cgollner** [comment]
I implemented this feature, but it doesn't have any option to show/hide it. I've been using it like this an like it. Let me know if you want a pull request with my code.

![muzei_wear_date](https://cloud.githubusercontent.com/assets/1053317/6133362/415705ce-b151-11e4-8368-89c03c904a90.png)

**Comment by ianhanniballake** [comment]
I've also implemented it in [my branch](https://github.com/ianhanniballake/muzei/tree/watchface_date) as well - just integrating in the settings work needs to be done at this point.

**Comment by cgollner** [comment]
Ok, cool!
