### ISSUE TITLE
Easy way to build without play-services

### ISSUE THREAD

**Issue by krt16s** [romannurik/muzei#127]
I tried to update this app on fdroid, a free/libre/open-source app "store", but failed to strip play-services dependency completly. Is there an easy way to build this app without play-services and wearable?

**Comment by romannurik** [comment]
To do that you'd basically need to rip out the wearable component entirely, so the wearable project, WearableController in the main project, and probably a couple other things. This isn't really something we want to officially support, so I'm closing this issue.

**Comment by ildar** [comment]
That's really sad.
May this issue stay open with "Feature Request" mark so that someone maybe want to get it back to f-droid?
@krt16s : the F-droid description should be updated. The old version in F-d has major issues on newer Android.

**Comment by akovalyov** [comment]
Bump for Feature Request.

**Comment by ianhanniballake** [comment]
Still not something we want to support, sorry.
