### ISSUE TITLE
Add Analytics

### ISSUE THREAD

**Issue by ianhanniballake** [romannurik/muzei#129]
Adding Analytics will help surface what actions are used most often, whether users are able to find the appropriate settings, and overall help build a better understanding of how people use Muzei. Ideally this should also allow slicing data by what art source is currently active (to narrow down issues caused by particular sources) and help with crash reporting by allowing segmentation by device and Android version.

This could be done via Google Analytics or indirectly through Google Tag Manager (which would feed data to Google Analytics).

**Comment by nyuszika7h** [comment]
If you're going to do this, please show a notice on the first start after the update to let users opt out if they want.

**Comment by ianhanniballake** [comment]
Basic, totally anonymous analytics have been added.
