### ISSUE TITLE
Image Centring (Single Pane Launchers)

### ISSUE THREAD

**Issue by symonds** [romannurik/muzei#13]
With the stock launcher on a Nexus 5 and only one pane only the far left of the image is visible.

Because the image is likely to be centred on the focal point. It would be nice if the image was centred in the launcher.

(x is the centre)
1 Pane:
[x]

2 Panes:
[ ]x[ ]

3 Panes:
[ ][x][ ]

And so on.

**Comment by nighto** [comment]
Is this the default nowadays? I just searched for this in Google and was going to open a bug in this exact terms, because it annoys me to have the image on the far left of my single home screen panel. 

Thanks.

**Comment by nighliber** [comment]
Maybe the Google Now Launcher changed this tendency on their side? Muzei wallpapers are left of center for me, but manually applied using default crop and pan they are centered. Nexus 6 on 5.1. For reference my lock screen is also left of center.

**Comment by Andrew-Quebe** [comment]
This a bit of an old issue but I'm still having the same issue as described in the first comment. Same device, same launcher.

**Comment by Odnetnin** [comment]
Also currently having the same issue on a Nexus 4 on 5.1 with Google Now Launcher.

**Comment by 77Belac77** [comment]
I'm also having trouble centering an image using Action Launcher 3.

**Comment by Chromelon** [comment]
Having trouble on the new Nexus Launcher

**Comment by ddaanngg** [comment]
Running Android 7.0 beta3 on the Nextbit Robin with the Google Now Launcher and this issue is still present, even with the latest 2.3 update.

**Comment by romannurik** [comment]
Google Now Launcher doesn't let wallpapers tell the difference between 1- and 2-page setups. So either one or the other won't work.

**Comment by TBJ** [comment]
I'm having the issue running Nova Launcher, especially after reboots. One pane set up. Adding and removing another pane will correctly center it with one homescreen pane, but it's something I have to do after every reboot.
