### ISSUE TITLE
Add intent to get to Advanced Settings

### ISSUE THREAD

**Issue by gbpackerfan95** [romannurik/muzei#135]
For one of my apps, I provide access to my muzei extension settings in the overflow menu of my app. This makes it easier for users, but I would also like to make it easy to access the Muzei advanced settings. I currently can't skip right to that, but can only get to the source selection screen via intents.

**Comment by ianhanniballake** [comment]
While not entirely obvious, adding the `Notification.INTENT_CATEGORY_NOTIFICATION_PREFERENCES` category to your Intent will skip immediately to the Advanced screen as per [line 96 of SettingsActivity](https://github.com/romannurik/muzei/blob/4e3efc3c706c86a0116749be75486d566c38d3e0/main/src/main/java/com/google/android/apps/muzei/settings/SettingsActivity.java#L96).

I do agree that making this more obvious would be helpful, but that might get you going in the short term.

**Comment by gbpackerfan95** [comment]
how do I add it exactly? This is what I have 
![image](https://cloud.githubusercontent.com/assets/2546510/6011787/cdaaf55c-ab0d-11e4-9f4e-e82648446eda.png)

**Comment by ianhanniballake** [comment]
From looking at the [Preference Intents documentation](http://developer.android.com/guide/topics/ui/settings.html#Intents), it does not look like setting a category is possible. We'll have to create a custom action to support that use case.

**Comment by gbpackerfan95** [comment]
It's currently really difficult for new users to know how to adjust this setting. This causes many, many reviews / emails about how my wallpapers are super blurry.

**Comment by ianhanniballake** [comment]
In Muzei 3.0, the SettingsActivity only allows users to customize the effects, so just opening the SettingsActivity will be enough to allow users to adjust the blur/dim/saturation settings.
