### ISSUE TITLE
Current Artwork Application

### ISSUE THREAD

**Issue by KrisGroove** [romannurik/muzei#139]
Hello, is any way to get current Artwork Application ( Muzei Plugin ) package?
I know I can get Artwork and Bitmap.

**Comment by ianhanniballake** [comment]
No currently there is no way to retrieve information about the source of the pictures., although I'd like to get to it at some point.

**Comment by ianhanniballake** [comment]
The [MuzeiContract.Sources](https://github.com/romannurik/muzei/blob/master/api/src/main/java/com/google/android/apps/muzei/api/MuzeiContract.java#L234) table will make this information available via the API, pending a future release of Muzei.
