### ISSUE TITLE
Wallpapers are jittery

### ISSUE THREAD

**Issue by karanrajpal14** [romannurik/muzei#141]
I just have two wallpapers set right now and they both appear to be jittery when the blur effect it applied. I have no idea of how to reproduce this as it happens randomly. 
![screenshot_2015-03-03-17-11-52 1](https://cloud.githubusercontent.com/assets/3253145/6477684/4813ed9e-c24c-11e4-8e9f-5e8cccaef308.png)
![screenshot_2015-03-03-17-12-00 1](https://cloud.githubusercontent.com/assets/3253145/6477688/55478110-c24c-11e4-9d74-6e14d75cf734.png)

**Comment by ianhanniballake** [comment]
If you come across this again, can you confirm the size of the original, unblurred wallpapers? I suspect they aren't a multiple of 4 in width or height, which causes the slight offset when transitioning between the two. There isn't any easy way of working around this unfortunately.

**Comment by romannurik** [comment]
This is also possibly related to the scaling the blurrer does for memory purposes. Blurred images are first scaled down and then blurred, so when the blur slider is not quite at zero but almost zero, you'll probably see some resampling artifacts.
