### ISSUE TITLE
getSharedPreferences is useless

### ISSUE THREAD

**Issue by Pitel** [romannurik/muzei#144]
I couldn't find any way to share preferences between `MuzeiArtSource` and `settingsActivity`.

I know there is `static getSharedPreferences`, but it returns `SharedPreferences`, and then I couldn't find a way to use them in `PreferenceFragment` (or `PreferenceActivity`).

So in all plugins I found on Github, people still do this in `MuzeiArtSource`:

``` java
SharedPreferences prefs = PreferenceManager.getDefaultSharedPreferences(this);
boolean b = prefs.getBoolean("derp", false);
```
###### Solutions
1. Add another `EXTRA` to the `Intent` providing preferences name.
2. Add another static method for getting preference name.

We will then be able to do this in `PreferenceFragment`:

``` java
getPreferenceManager().setSharedPreferencesName("PrefsName");
```

Sure, we can use `muzeiartsource_PrefsName` these days, but it's undocumented. So maybe, document it is possible soulution number 3.

**Comment by romannurik** [comment]
Good points; it might be useful to do option 3.

**Comment by ianhanniballake** [comment]
We've decided to remove the shared preferences APIs in Muzei 3.0's new API as Muzei no longer needs to store any specific shared preferences and it is better that you, as the developer, control your own shared preferences as needed.
