### ISSUE TITLE
Crashes on Android 5.1

### ISSUE THREAD

**Issue by NazimAmin** [romannurik/muzei#145]
Crashes on Android 5.1 as soon as the app is launched.

**Comment by ianhanniballake** [comment]
You'll need to include more details, such as a full stack trace, to help narrow down the issue.

**Comment by NazimAmin** [comment]
Hope this helps. 

I/ActivityManager(17570): Start proc 29620:net.nurik.roman.muzei/u0a135 for activity net.nurik.roman.muzei/com.google.android.apps.muzei.MuzeiActivity
I/ActivityManager(17570): Killing 26027:com.google.android.calendar/u0a48 (adj 15): empty #17
D/OpenGLRenderer(29620): Use EGL_SWAP_BEHAVIOR_PRESERVED: true
D/Atlas   (29620): Validating map...
V/WindowManager(17570): Adding window Window{3a6fdbf2 u0 net.nurik.roman.muzei/com.google.android.apps.muzei.MuzeiActivity} at 8 of 14 (after Window{b26cf3d u0 com.google.android.feedback/com.google.android.feedback.PreviewActivity})
I/MuzeiArtSource(29620): Scheduling next artwork (source FeaturedArt) at Sun Mar 29 22:02:33 EDT 2015
I/Adreno-EGL(29620): <qeglDrvAPI_eglInitialize:410>: QUALCOMM Build: 10/28/14, c33033c, Ia6306ec328
I/OpenGLRenderer(29620): Initialized EGL, version 1.4
D/OpenGLRenderer(29620): Enabling debug mode 0
I/ActivityManager(17570): Displayed net.nurik.roman.muzei/com.google.android.apps.muzei.MuzeiActivity: +677ms
I/MuzeiArtSource(29620): Scheduling next artwork (source FeaturedArt) at Sun Mar 29 22:15:42 EDT 2015
D/Event   (29620): No subscribers registered for event class com.google.android.apps.muzei.event.CurrentArtworkDownloadedEvent
D/Event   (29620): No subscribers registered for event class de.greenrobot.event.NoSubscriberEvent
D/Event   (29620): No subscribers registered for event class com.google.android.apps.muzei.event.CurrentArtworkDownloadedEvent
D/Event   (29620): No subscribers registered for event class de.greenrobot.event.NoSubscriberEvent
D/Event   (29620): No subscribers registered for event class com.google.android.apps.muzei.event.CurrentArtworkDownloadedEvent
D/Event   (29620): No subscribers registered for event class de.greenrobot.event.NoSubscriberEvent
V/RenderScript_jni(29620): RS native mode
E/AndroidRuntime(29620): FATAL EXCEPTION: GLThread 8768
E/AndroidRuntime(29620): Process: net.nurik.roman.muzei, PID: 29620
E/AndroidRuntime(29620): android.support.v8.renderscript.RSRuntimeException: Failure to create platform RenderScript context
E/AndroidRuntime(29620): 	at android.support.v8.renderscript.RenderScriptThunker.create(RenderScriptThunker.java:68)
E/AndroidRuntime(29620): 	at android.support.v8.renderscript.RenderScript.create(RenderScript.java:997)
E/AndroidRuntime(29620): 	at android.support.v8.renderscript.RenderScript.create(RenderScript.java:1055)
E/AndroidRuntime(29620): 	at android.support.v8.renderscript.RenderScript.create(RenderScript.java:1041)
E/AndroidRuntime(29620): 	at com.google.android.apps.muzei.util.ImageBlurrer.<init>(ImageBlurrer.java:39)
E/AndroidRuntime(29620): 	at com.google.android.apps.muzei.render.MuzeiBlurRenderer$GLPictureSet.load(MuzeiBlurRenderer.java:359)
E/AndroidRuntime(29620): 	at com.google.android.apps.muzei.render.MuzeiBlurRenderer.setAndConsumeBitmapRegionLoader(MuzeiBlurRenderer.java:272)
E/AndroidRuntime(29620): 	at com.google.android.apps.muzei.render.RenderController$2$1.run(RenderController.java:98)
E/AndroidRuntime(29620): 	at com.google.android.apps.muzei.render.GLTextureView$GLThread.guardedRun(GLTextureView.java:1238)
E/AndroidRuntime(29620): 	at com.google.android.apps.muzei.render.GLTextureView$GLThread.run(GLTextureView.java:1015)
W/ActivityManager(17570):   Force finishing activity 1 net.nurik.roman.muzei/com.google.android.apps.muzei.MuzeiActivity

**Comment by NazimAmin** [comment]
Pardon the RenderScript error is within AOSP and not Muzei. Closing the issue.

**Comment by fat-tire** [comment]
fwiw, here it is on note 4, 5.1 (cyanogenmod):

F/libc    (13215): Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 13263 (GLThread 1170)
I/Timeline(  885): Timeline: Activity_windows_visible id: ActivityRecord{214d18a0 u0 net.nurik.roman.muzei/com.google.android.apps.muzei.settings.SettingsActivity t1025} time:11276523
I/DEBUG   (13118): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
I/DEBUG   (13118): Build fingerprint: 'samsung/trltetmo/trltetmo:5.1/LMY47E/N910TUVU1ANJ7:user/release-keys'
I/DEBUG   (13118): Revision: '12'
I/DEBUG   (13118): ABI: 'arm'
I/DEBUG   (13118): pid: 13215, tid: 13263, name: GLThread 1170  >>> net.nurik.roman.muzei <<<
I/DEBUG   (13118): signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
I/DEBUG   (13118):     r0 00000000  r1 9b62d040  r2 00000780  r3 00000000
I/DEBUG   (13118):     r4 9d98505c  r5 00000000  r6 00000280  r7 9b62d000
I/DEBUG   (13118):     r8 00000000  r9 00000000  sl 9b62d280  fp 00000780
I/DEBUG   (13118):     ip 00000013  sp 9d4fd3d0  lr 00000280  pc b6da30b0  cpsr 20030030
I/DEBUG   (13118): 
I/DEBUG   (13118): backtrace:
I/DEBUG   (13118):     #00 pc 000110b0  /system/lib/libc.so (__memcpy_base+227)
I/DEBUG   (13118):     #01 pc 0000027c  <unknown>
W/SurfaceFlinger(  311): couldn't log to binary event log: overflow.
W/ActivityManager(  885):   Force finishing activity 1 net.nurik.roman.muzei/com.google.android.apps.muzei.settings.SettingsActivity
I/DEBUG   (13118): 
I/DEBUG   (13118): Tombstone written to: /data/tombstones/tombstone_01


There is a long boring tombstone as well.. here's part of it:

*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'samsung/trltetmo/trltetmo:5.1/LMY47E/N910TUVU1ANJ7:user/release-keys'
Revision: '12'
ABI: 'arm'
pid: 13074, tid: 13104, name: GLThread 1157  >>> net.nurik.roman.muzei <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
    r0 00000000  r1 9f4ff040  r2 00000780  r3 00000000
    r4 ac6ee05c  r5 00000000  r6 00000280  r7 9f4ff000
    r8 00000000  r9 00000000  sl 9f4ff280  fp 00000780
    ip 00000013  sp a12ff3d0  lr 00000280  pc b6da30b0  cpsr 20030030
    d0  0000000000000000  d1  0000000000000000
    d2  0000000000000000  d3  0000000000000000
    d4  0000000000000000  d5  0000000000000000
    d6  0000000000000000  d7  0000000000000000
    d8  3f4000003f400000  d9  0000000044200000
    d10 3feaf456e91b52c8  d11 3fd5e8add236a58f
    d12 3fe5e8add236a58f  d13 000000003ef00000
    d14 0000000000000000  d15 0000000000000000
    d16 0000000000000000  d17 0000000000000000
    d18 0000000000000000  d19 0000000000000000
    d20 0000000000000000  d21 0000000000000000
    d22 0000000000000000  d23 0000000000000000
    d24 0000000000000000  d25 0000000000000000
    d26 0000000000000000  d27 0000000000000000
    d28 0000000000000000  d29 0000000000000000
    d30 0000000000000000  d31 0000000000000000
    scr 28000011

backtrace:
    #00 pc 000110b0  /system/lib/libc.so (__memcpy_base+227)
    #01 pc 0000027c  <unknown>

stack:
         a12ff390  b4ad0190  
         a12ff394  b48a5080  
         a12ff398  00000000  
         a12ff39c  b48a5080  
         a12ff3a0  00000000  
         a12ff3a4  ac79b247  /system/lib/libRSCpuRef.so (android::renderscript::RsdCpuScriptIntrinsic::RsdCpuScriptIntrinsic(android::renderscript::RsdCpuReferenceImpl*, android::renderscript::Script const*, android::renderscript::Element const*, RsScriptIntrinsicID)+42)
         a12ff3a8  00000000  
         a12ff3ac  0000000c  

etc.

**Comment by ianhanniballake** [comment]
Re-opening as this is coming up again in Muzei 2.3. Should evaluate if Muzei can use the [workaround here](https://code.google.com/p/android/issues/detail?id=61159#c5)

**Comment by ianhanniballake** [comment]
Based on recommendations from the Renderscript team, put in fixes to allocations in #380, included in Muzei 2.3.1 Beta 5, which should significantly help with these issues.
