### ISSUE TITLE
Muzei for Lockscreen in LG G2/G3

### ISSUE THREAD

**Issue by InternetWanderer** [romannurik/muzei#150]
Hi,

My apologies if this is a wrong forum to ask this. This is my first time using Github and so forgive me if I am doing something wrong

I love Muzei and have been using it right from the first week it was released. I recently shifted to a LG G2 and LG G3 (Yes, I use both - one for work and one for personal). I realized that Muzei doesn't change the lockscreen wallpaper like it did in my earlier Samsung device.

Can you please consider adding the feature where Muzei can change both the Homescreen and Lockscreen wallpaper on LG G2/G3 stock ROM?

Thanks for the wonderful app

**Comment by ianhanniballake** [comment]
LG G2/G3 do not support live wallpapers on the lock screen - this is a manufacturer decision and not something that Muzei can work around unfortunately.
