### ISSUE TITLE
Add parallax effect based on the device rotation?

### ISSUE THREAD

**Issue by SolusSoftworks** [romannurik/muzei#151]
It would be be quite nice to have an effect where the image shifts slightly based on the physical rotation of the device. An extra slider that controlled the offset (set at 0 by default for no movement) would be perfect. 

This option would be great for users that only use a single screen but still want the background to have some movement or those that use launchers which handle things differently. It would also help the static items to stand out more on the moving background.

**Comment by romannurik** [comment]
This might be cool, but I don't think the battery performance implications warrant it for the basic version of Muzei :-/ We have the benefit right now of only rendering when swiping on your home screen; if we were constantly rendering in response to accelerometer events, it'd be a pretty rough on the battery.
