### ISSUE TITLE
Causing UI Crash in 5.0

### ISSUE THREAD

**Issue by chessmastah** [romannurik/muzei#154]
After installing the app, the UI crashes randomly with the message: "system.ui has stopped"

Using Asus Zenfone 2.

**Comment by BenMcCluskey** [comment]
I have the same problem in 5.1.1 on Oneplus One

**Comment by ianhanniballake** [comment]
Generally, nothing an app should be able to do should crash the System UI, so this seems like an issue with the manufacturer's customizations. Without a stack trace, it is impossible to know what could be the issue.
