### ISSUE TITLE
Local art source requires `onUpdate` when created

### ISSUE THREAD

**Issue by Fleker** [romannurik/muzei#158]
I noticed last night that I was unable to display my local art source in Muzei, so I added in some log messages. When I went to the art picker and chose my source, the log would print that my service was created and then Muzei crashes ( same error as #45 ).

After spending some time debugging my art source, I found the solution was to manually add an `onUpdate` call in my `onCreate` method:

     @Override
     public void onCreate() {
         super.onCreate();
         Log.d(TAG, "Created");
         removeAllUserCommands();
         onUpdate(0);
     }

I'm not sure if this is intentional, but it didn't have that line in the example, so this should be documented if that is the case.

**Comment by ianhanniballake** [comment]
Nope, calling `onUpdate(0)` is not required. Neither of the built in sources do this in the current codebase.
