### ISSUE TITLE
"Wear only" mode

### ISSUE THREAD

**Issue by andreq** [romannurik/muzei#163]
It would be nice to have a Android Wear only mode that would fetch smaller version of the photo and update even tho the user didn't set Muzei as his background.

I personal just want my watch BG to be updated every now and then, but would like to keep my current background on my phone. As of right now, it seem like I need to "start" Muzei  every morning for it to kick refresh every X minutes.

**Comment by ianhanniballake** [comment]
Yes, this will be covered in #103 which will decouple the loading framework from the phone wallpaper itself.
