### ISSUE TITLE
Expand "Gray" slider to saturate

### ISSUE THREAD

**Issue by Supuhstar** [romannurik/muzei#164]
It's beautiful when blurred images are saturated. Please allow the current "Gray" slider to also go the other way into saturated :D

**Comment by romannurik** [comment]
Hm, I'd want to avoid *adding* saturation... that can blow out colors and such. You can always choose art sources that have higher-saturated images?

**Comment by Supuhstar** [comment]
The slider wouldn't have to go too high. And even if it did, blowing out the colors can look great when it's also blurred!

Basically what I'm trying to emulate is macOS's "vibrancy" effect: https://cdn.arstechnica.net/wp-content/uploads/2014/10/vibrancy@2x.png
They do this thing where it's saturated, then blurred, then darkened or lightened.

Just try it :D
If it doesn't look good then no harm done but I bet it'll look great and then that's an easy feature add :D

**Comment by romannurik** [comment]
hrm, will look into it

**Comment by Supuhstar** [comment]
Awesome, thank you so much!
