### ISSUE TITLE
Image download problem. 

### ISSUE THREAD

**Issue by tasomaniac** [romannurik/muzei#166]
I am using an online source that I cannot control. Some of the images are given with `Content-Type: application/octet-stream` which makes Muzei not working because of this line https://github.com/romannurik/muzei/blob/master/main/src/main/java/com/google/android/apps/muzei/util/IOUtil.java#L120

It is actually good for protection. But the problem is that after that `IOException` the last background image becomes stuck until the user manually opens the app and click next. 

The app behaves like this is a `RetryError` and retries the image infinitely. Instead it should try to load the next image.

**Comment by ianhanniballake** [comment]
We no longer check Content-Type so this should indirectly solve this issue

**Comment by tasomaniac** [comment]
Thanks for the heads up. I will check my wallpaper source.
