### ISSUE TITLE
Feature request: Allow artwork download only on WiFi

### ISSUE THREAD

**Issue by litera** [romannurik/muzei#168]
It would be great if one could set Muzei app to only download new artwork when phone is connected to a WiFi network because if one is roaming (with data enabled for emergency data only), then they must set a static background on the device to prevent Muzei from downloading artwork on a daily basis.

**Comment by ianhanniballake** [comment]
Dup of #59

**Comment by litera** [comment]
Right. Thanks. I've checked a few other issues but I somehow missed that one. It seems the exact duplicate, yes. Hopefully it'll be soon resolved.
