### ISSUE TITLE
Double tap not working?

### ISSUE THREAD

**Issue by bonjourlemonde** [romannurik/muzei#170]
Hi,

Love the app!

Unfortunately, double tap on home screen to focus is not working for me.
(Samsung Galaxy S6 Edge, non-rooted, stock ROM, no custom launchers)

Any ideas?

Thanks,
Jakob

**Comment by ianhanniballake** [comment]
Does it work if you load the [Google Now Launcher](https://play.google.com/store/apps/details?id=com.google.android.launcher)? If so, then this would be a problem with the included launcher not sending the [COMMAND_TAP](http://developer.android.com/reference/android/app/WallpaperManager.html#COMMAND_TAP) to Muzei.

**Comment by ianhanniballake** [comment]
This is most likely an issue with the launcher not supporting the standard commands that live wallpapers use to detect taps. Feel free to leave feedback with the manfuacturer, launcher maker.
