### ISSUE TITLE
Recommended rotation (i. e. update) period

### ISSUE THREAD

**Issue by ming13** [romannurik/muzei#178]
It would be great to have a Muzei-wide option to specify a recommended update period. This and #59 [seem to be](https://www.reddit.com/r/Android/comments/3jxz5q/earth_view_from_google_if_youre_looking_for_more/) highly demanded options. I think it should be an application-wide setting, because at this point extensions are forced to implement it themselves.

Implementation ideas.
- Create a setting at the UI.
- Add a method `MuzeiArtSource.html#scheduleUpdate()`. Please notice that this method has no parameters. This way the application-wide setting will be used instead extension-wide one.
- A more radical approach is to replace `MuzeiArtSource.html#scheduleUpdate(long)` with `MuzeiArtSource.html#scheduleUpdate()`, but it will break all existing extensions.

**Comment by Ivoz** [comment]
+1. Some extensions have a good update period, some are very limited, it's very hit and miss. Would be nice to see an easy customizable picker that set every app's period.

**Comment by ianhanniballake** [comment]
Muzei 3.0 introduces a centralized Auto Advance schedule for sources that are built with the new API. Existing sources will keep their current behavior.
