### ISSUE TITLE
HTTP Basic Authentication

### ISSUE THREAD

**Issue by Andrew-Quebe** [romannurik/muzei#181]
@ianhanniballake does Muzei support links that have authentication attached to them? That is, going to a URL that is protected with htaccess authentication. I'm loading in artwork from a json file and it's imperative that I use authentication. 

Here's an example URL of what I mean: http://ValidUsername:ValidPassword@www.example.com

When I try to put this as a URL, Muzei and my app crash. Any ideas?

**Comment by romannurik** [comment]
This isn't supported. What's the use case? Why do you need the authentication?

**Comment by Andrew-Quebe** [comment]
For use with a paid app where wallpapers are loaded in via URL but locked when accessing them from a web browser to prevent right-click, save as.
On Oct 8, 2015 5:15 AM, Roman Nurik <notifications@github.com> wrote:This isn't supported. What's the use case? Why do you need the authentication?

**Comment by romannurik** [comment]
Ah. Muzei caches images on the sdcard so they're not really protected anyway :-/

**Comment by Andrew-Quebe** [comment]
Well that's true. But I'd imagine it's harder to gain access to said cache than it is to go on a website. As it is now, I've just randomized a folder name where the wallpapers are stored but I wish this existed in the lib somehow.

(I could attempt to add it but have no idea where to start!)

**Comment by romannurik** [comment]
The cache is pretty easy to find on the sdcard, but at any rate, randomizing a folder name would be fine, and alternatively you can just create a custom content provider that does the HTTP fetches and passes the contents to Muzei (both unauthenticated http:// and content:// URIs are supported by Muzei)
