### ISSUE TITLE
Use local files rather than remote urls

### ISSUE THREAD

**Issue by adrianaisemberg** [romannurik/muzei#182]
Artwork.Builder requires a url to a downloadable image from the web.
Can I use a locally saved file, like:

    publishArtwork(new Artwork.Builder()
        ...
        .imageUri(Uri.fromFile(new File("/sdcard/some_wallpaper.png")))
        ...
        .build());

My motivation is to generate a bitmap, save it and pass the url for the saved file to Muzei.

Thanks

**Comment by romannurik** [comment]
You can do this but only using content URIs because otherwise Muzei would need additional permissions.

See
http://api.muzei.co/reference/com/google/android/apps/muzei/api/Artwork.Builder.html#imageUri(android.net.Uri)

**Comment by adrianaisemberg** [comment]
Thanks. I'll investigate.




Adrian Aisemberg

Get Tapet for Android
<https://play.google.com/store/apps/details?id=com.sharpregion.tapet>

**Comment by ianhanniballake** [comment]
Please do read the full sharing file training, which goes into the details of using FileProvider to do exactly what you need: http://developer.android.com/training/secure-file-sharing/index.html

**Comment by adrianaisemberg** [comment]
Thanks. I just released Tapet v4.65 which adds support for Muzei.

Regards,
Adrian




Adrian Aisemberg

Get Tapet for Android
<https://play.google.com/store/apps/details?id=com.sharpregion.tapet>
