### ISSUE TITLE
Feature Request: Allow user to pause updating

### ISSUE THREAD

**Issue by jdrews** [romannurik/muzei#184]
Allow a user to pause the updating of a wallpaper if they find one they really like. The intent of this feature request is to allow users to stop the automatic updating indefinitely when they find a background that appeals to them. I would expect there would be a pause button when clicking on the Muzei app.

**Comment by romannurik** [comment]
It's not ideal, but you can always visit muzei.co/archive, download the original-quality image, and manually set it as wallpaper. Prefer not to specially add pause for now (sorry I'm responding a year late!)

**Comment by ianhanniballake** [comment]
In the Muzei 2.3 Beta, you can also select previously displayed artwork from within the My Photos source.

**Comment by Xalaxis** [comment]
I'd like to suggest this issue be reopened.  For users such as I using custom sources, it cannot be guaranteed that the source itself provides a history function.  In addition, often I wish to simply pause the wallpaper change for a few days at most before resuming.  To manually save the image would quickly become a chore if done on a regular basis.

From a technical perspective, are there any particular barriers to simply halting the requests for updates from the source?

**Comment by ianhanniballake** [comment]
In Muzei 3.0, the loading schedule for sources built on the [new API](https://medium.com/@ianhlake/muzei-3-0-and-the-new-api-4fd3d6133db6) is controlled from within Muzei's Auto Advance settings and not by individual sources, which will make it possible to pause any source just by disabling Auto Advance.
