### ISSUE TITLE
Allow flexability in options for lockscreen/homescreen image adjustments.

### ISSUE THREAD

**Issue by Ivoz** [romannurik/muzei#185]
Apparently I am different from some users (e.g #1) and would like my image _blurred_ while the lockscreen is active, while the homescreen image is sharp. To indicate visually to me that one of them is an "inactive" state and the other is "active" and in focus. But that's just a preference.

How I would invision enabling this would be to do away with the "Apply blur on lockscreen" checkbox, and instead put a simple 2-option select on top of the sliders, one being for lockscreen, one being for homescreen. Then the sliders apply the values you set for the currently active option. The picture behind would show the preview same as current.

In this way people could change how the image appears on either to their hearts content - maybe you want your image faded to greyscale when your lockscreen is up, but then restored to full color when you unlock (or visa versa)?

Cheers for the great app so far.

**Comment by xcom923** [comment]
I'm the same way, I want to have a way to have an effect on the lock screen. Hell it would be awesome if nova could do an effect when the drawer is pulled out to (sorry for going off the rails)

**Comment by ianhanniballake** [comment]
This was fixed in #551 and is available in [Muzei 3.0 Alpha 2](https://plus.google.com/+IanLake/posts/DiKA5FbZ443)
