### ISSUE TITLE
Double tap not working on BlackBerry Priv (Android 5.1.1)

### ISSUE THREAD

**Issue by nerfslinger** [romannurik/muzei#186]
Blur can be turned on/off on the lock screen successfully, but on the home screen double tap has no effect and image remains blurred. Love the app and had been using it on my previous phone (Note 4).

Thanks.

**Comment by ianhanniballake** [comment]
Does it work if you load the [Google Now Launcher](https://play.google.com/store/apps/details?id=com.google.android.launcher)? If so, then this would be a problem with the included launcher not sending the [COMMAND_TAP](http://developer.android.com/reference/android/app/WallpaperManager.html#COMMAND_TAP) to Muzei.

**Comment by AveSharia** [comment]
I am not nerflinger, but I had the same problem on my Note 5 running the stock TouchWiz launcher. Switching to Google Now Launcher does solve the problem. I didn't find anything by Googling around for problems with Touchwiz not sending COMMAND_TAP, only some reports of it sending COMMAND_TAP when it shouldn't from back in the S3 days.

Hope that helps!

**Comment by ianhanniballake** [comment]
I suspect the same root cause as #170
