### ISSUE TITLE
App not launchable from system live wallpapers - System says "App isn't installed"

### ISSUE THREAD

**Issue by Qrbaker** [romannurik/muzei#191]
Tested on a rooted moto X 2013, with Lollipop 5.1

This issue occurs with both the Google Now launcher as well as Nova Launcher.

Strangely, a third party app (backdrops) can access the Muzei settings, but Muzei doesn't actually activate.

![Image of issue](http://i.imgur.com/tMzLUcY.jpg)

**Comment by Qrbaker** [comment]
Issue was due to an android live wallpaper apk not being installed on the phone.

**Comment by PushyPants** [comment]
is there a link to the stock apk? I'm running into the same issue on a different device.
