### ISSUE TITLE
Decouple date format on watch from locale

### ISSUE THREAD

**Issue by muro** [romannurik/muzei#192]
Due to memory limitations of watches, they often have a more limited set of supported locales - e.g. for moto360 it's lited at https://motorola-global-portal.custhelp.com/app/answers/detail/a_id/100837
The watch will default to English US if your phone uses any other locale - setting e.g. date format to a different one than the phone displays. It would be nice to send the date format from the phone to the watch - either by using the phone's locale or allow to override it.

**Comment by ianhanniballake** [comment]
The next beta, Muzei 2.5.0 Beta 5, has switched the date to using the date complication on API 24+, which controls the date formatting. We won't be pursuing any date format setting for API 23 watches.
