### ISSUE TITLE
Gradle Syncing Error

### ISSUE THREAD

**Issue by jamesblent** [romannurik/muzei#198]
I pulled project and imported in Android Studio. Gradle sync processed but i'm getting following error, building debug APK for testing. Please help me out.Thanks
**Error:Execution failed for task ':api:javadoc'.
> A problem occurred starting process 'command './javadoc-scripts/generate_javadoc.sh''**

**Comment by ianhanniballake** [comment]
You'll want to `Make module 'main'` or whatever you're interested in - generating the javadoc is not a requirement to build Muzei itself
