### ISSUE TITLE
Wallpaper not centralised

### ISSUE THREAD

**Issue by 1990clb** [romannurik/muzei#199]
This issue has been fixed previously, but now is happening again, probably due to some Google changes. It would be good to have it looked at again.

With the stock launcher on a Nexus 6p and only one pane, only the far left of the image is visible.

Because the image is likely to be centred on the focal point, it would be nice if the image was centred in the launcher.

(x is the centre)
1 Pane:
[x]

2 Panes:
[ ]x[ ]

3 Panes:
[ ][x][ ]

And so on.

**Comment by romannurik** [comment]
I've looked into this and unfortunately, AFAICT, there's no way for live wallpapers to differentiate between 1- and 2-page home screens with Google Now / Pixel Launcher. So either the 1- or 2-page scenarios will be suboptimal :-/
