### ISSUE TITLE
(Request) synced wallpapers across devices

### ISSUE THREAD

**Issue by Guitargler** [romannurik/muzei#200]
I use Muzei on my phone, watch, and tablet. I'm using the same source and the same settings for my phone and tablet, but they're never on the same image. Genuinely don't know how hard this would be to implement, but it's something I'd love to see.

**Comment by ianhanniballake** [comment]
The built in featured art source has some jitter in its reloading timing to prevent overloading the Muzei image backend and the gallery art source is local (we don't store images on external servers, etc), making syncing across devices infeasible for those.

A third party art source could certainly do this with their own login system as Muzei does support updating the wallpaper on demand, but that would be on the external developer to provide.
