### ISSUE TITLE
Question about Customize Option

### ISSUE THREAD

**Issue by BedHead911** [romannurik/muzei#203]
In the main menu of muzei (when you choose image from your own gallery) there are two buttons in bottom right hand corner. One button changes the wallpaper. The other button opens a menu where the only option is "customize"

I wanted to know if you're planning on adding more options to this menu. If not, can pressing that button automatically default to "customize"? It seems like a redundant extra amount of clicks.

**Comment by ianhanniballake** [comment]
Individual art sources (such as the included featured art source) can provide custom actions that appear in that menu.

There is ongoing work to restructure the navigation of the app though!
