### ISSUE TITLE
Quadratic bezier curves support

### ISSUE THREAD

**Issue by eskalera** [romannurik/muzei#205]
I'm trying to use your [SVGPathParser](https://github.com/romannurik/muzei/blob/master/main/src/main/java/com/google/android/apps/muzei/util/SvgPathParser.java) but it throws an error when trying to parse paths with Q commands for Quadratic bezier curves.

Is there any reason they haven't been included? Any solution to this?

Thanks.

**Comment by romannurik** [comment]
No reason except the Muzei code didn't need it; feel free to submit a pull request if you write it :)

**Comment by eskalera** [comment]
I haven't got to fork the repo, because the SVGPathParser was all I needed. Not sure if this is politically correct in github. Please tell me if it isn't.

But in case anyone comes across the same issue as me. Here is my approach to tackle the problem. I have just added this after [line 158](https://github.com/romannurik/muzei/blob/master/main/src/main/java/com/google/android/apps/muzei/util/SvgPathParser.java#L158)

`case 'Q':
                case 'q': {
                    // curve command
                    if (mCurrentPoint.x == Float.NaN) {
                        throw new ParseException("Relative commands require current point", mIndex);
                    }

                    while (advanceToNextToken() == TOKEN_VALUE) {
                        consumeAndTransformPoint(tempPoint1, relative);
                        consumeAndTransformPoint(tempPoint2, relative);
                        p.quadTo(tempPoint1.x, tempPoint1.y, tempPoint2.x, tempPoint2.y);
                    }
                    mCurrentPoint.set(tempPoint2);
                    break;
                }`

**Comment by ianhanniballake** [comment]
There's an 'Edit' button in the upper right of the SVGPathParser file which should allow you to easily create a pull request and submit the code. I'd suggest adding this after line 151 though (and keep the close command as the last one).

**Comment by eskalera** [comment]
Thanks @ianhanniballake. I've just created my first pull request in github thanks to you. :)
#206

**Comment by romannurik** [comment]
Thank you!
