### ISSUE TITLE
Muzei Archive site does not load: No 'Access-Control-Allow-Origin' header

### ISSUE THREAD

**Issue by ianhanniballake** [romannurik/muzei#240]
When going to http://muzeiapi.appspot.com/archive/2016/8

I receive the following errors in the Console and nothing loads:
XMLHttpRequest cannot load http://storage.googleapis.com/muzeifeaturedart/archivemeta/20160819.txt. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://muzeiapi.appspot.com' is therefore not allowed access.
XMLHttpRequest cannot load http://storage.googleapis.com/muzeifeaturedart/archivemeta/201607.txt. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://muzeiapi.appspot.com' is therefore not allowed access.

**Comment by ianhanniballake** [comment]
No pictures on the web still :(

**Comment by romannurik** [comment]
Whoops, I wonder what happened there :-/ Will look into it asap.

**Comment by romannurik** [comment]
Oh, that's the problem, you need to access it from muzei.co instead of muzeiapi.appspot.com... http://www.muzei.co/archive/
