### ISSUE TITLE
Google Play Update?

### ISSUE THREAD

**Issue by onedr0p** [romannurik/muzei#247]
I'm asking this here, because I bet some other people have this question. The version in the play store is pretty out dated. Any chance of a update / beta channel for this wonderful app? I don't mind compiling from source, but having the update be streamlined would be awesome.

**Comment by ianhanniballake** [comment]
Coming soon! Make sure to join the [Muzei Live Wallpaper G+ Community](https://plus.google.com/u/0/communities/114043146173681149763) to get announcements and access to the beta

**Comment by onedr0p** [comment]
Awesome, thanks! Looking forward to the ~2 years of improvements.

**Comment by ianhanniballake** [comment]
A [beta of Muzei 2.3](https://plus.google.com/+IanLake/posts/4ikHrFaeWnF) is now available to community members! Public release to come.
