### ISSUE TITLE
DownloadArtworkTask openUri request header not support

### ISSUE THREAD

**Issue by gnastnosaj** [romannurik/muzei#256]
can not download source need request header

**Comment by ianhanniballake** [comment]
You can certainly download the artwork yourself and then send a [FileProvider](https://developer.android.com/reference/android/support/v4/content/FileProvider.html) URI to Muzei.

This model (your app downloading the art and passing it to Muzei) is going to be model in the next revision of the API (not yet checked in).

**Comment by gnastnosaj** [comment]
thanks
