### ISSUE TITLE
Brief flicker of settings cog when changing from the featured art source to the gallery source

### ISSUE THREAD

**Issue by romannurik** [romannurik/muzei#310]
When switching sources, the settings cog sometimes flickers:

![change-sources-flicker](https://cloud.githubusercontent.com/assets/100155/21428648/23428072-c829-11e6-8f5a-1376de28fb0d.gif)

This doesn't occur when changing from Gallery to Featured Art, but does occur vice versa.

**Comment by ianhanniballake** [comment]
Looks be caused by selecting a source with a setup activity (and the `onResume()` caused by it).
