### ISSUE TITLE
Muzei Force closes on Android 7.1.1 on activating the Autotools source

### ISSUE THREAD

**Issue by dvddoo** [romannurik/muzei#311]
On my Galaxy S5 running CM 7.1.1 Muzei force closes on activating the Autotools source. I need to clear the Muzei data before the app is accessible again. Do you have any suggestions?

**Comment by ianhanniballake** [comment]
Do you have a stacktrace? What version of Muzei are you running?

**Comment by dvddoo** [comment]
Issue can be closed now. I cleared the Autotools data and Muzei is working normal now.
