### ISSUE TITLE
Short flicker of lock screen overlay when unlocking phone with muzei set as home AND lock screen

### ISSUE THREAD

**Issue by zmokhiber** [romannurik/muzei#312]
Hello,

This is my first time using Github, so not sure if this is the correct place to ask about this, but I can't seem to find anyone else having this issue, so I thought I would make a post about it. 

I just downloaded muzei, and I love it so far! However, I've noticed a small and slightly aggravating flicker every time i unlock my phone. 

The lock screen overlay seems to hang around for a bit when unlocking the phone, but only if muzei is set as the lock screen and the home screen wallpaper. 

FYI: I'm using a galaxy s7 with action launcher 3. (note that the same thing happens when using touchwiz as my launcher)

Here is a gif of the unlock animation using the default samsung lock screen:

![videotogif_2017 01 03_14 16 45 1](https://cloud.githubusercontent.com/assets/24900126/21619975/147e0250-d1c0-11e6-8806-46188d7ca652.gif)

And here is the unlock animation using muzei as the lock and home screen wallpaper. I've tried messing around with a bunch of different settings, but this delay on the lock screen icons happens every time.

![videotogif_2017 01 03_14 18 29 1](https://cloud.githubusercontent.com/assets/24900126/21619971/0b93efb0-d1c0-11e6-9331-d75f71badead.gif)

Thanks for the great app!

**Comment by romannurik** [comment]
Hm, that's weird. Does the same occur if you use a different live wallpaper? Muzei shouldn't affect anything related to the actual lock screen and home screen, just the wallpaper behind both of them, so I'm almost certain it's something in the OS/launcher/elsewhere..

**Comment by zmokhiber** [comment]
Hmmm yeah I think you are right. I tested it out with other live wallpapers and the same thing happened. 

I'll see if I can find out why this is happening elsewhere. Thanks for responding!
