### ISSUE TITLE
Dim/blur/grey settings not applying on user change in settings

### ISSUE THREAD

**Issue by romannurik** [romannurik/muzei#320]
On my Pixel running 7.1.1, using Beta 7, dragging any of the sliders in advanced settings doesn't seem to take any effect 😕

**Comment by romannurik** [comment]
Clearing data solves the problem for me

**Comment by ianhanniballake** [comment]
Did you try:
1. Hitting the 'Reset sliders' option?
2. Changing to a different wallpaper and then back to Muzei?
3. Restarting your device?

I'm not sure why any of those things would cause the sliders to not work though.

**Comment by romannurik** [comment]
Tried to reset sliders but that didn't fix it. Didn't try the other two, but clearing data fixed it. My guess is a restart would've fixed it. Oh well :-/

**Comment by ianhanniballake** [comment]
Another report on [this Google+ post](https://plus.google.com/+IanLake/posts/axRRodk1QuU), investigating.
