### ISSUE TITLE
Huge bandwidth usage

### ISSUE THREAD

**Issue by jeffreydelooff** [romannurik/muzei#33]
![screenshot_2014-02-20-14-31-45](https://f.cloud.github.com/assets/263346/2218759/a7f77a22-9a35-11e3-9789-712caa8b2e98.png)
(Mirror: http://i.imgur.com/exolwoT.png)

I think this was an Alarm Managing issue. Yesterday I changed my date to today's date to test a different app. Then today this happened. Ouch. Good thing I was on Wifi!

After a reboot everything went back to normal. Am monitoring the usage now.

**Comment by cbeyls** [comment]
I just had a similar issue on my Nexus 5 on Android 5.0.1. The new wallpaper kept loading in a loop in the background for one day, consuming about 38GB of data on my internet connection... I ocured with some wallpapers but not all and was reproductible after a reboot. While loading the wallpaper in Muzei, I see the animated loading logo appear and disappear in a loop for the incriminated wallpaper.

Then I uninstalled and reinstalled Muzei and the problem disappeared; I could load the failing wallpapers. Which makes me think it's probably a cache issue that you should investigate.

**Comment by ianhanniballake** [comment]
Muzei's sync infrastructure has been rebuilt entirely from the ground up, obsoleting this issue.

In addition, Muzei 3.0's new API moves downloading artwork to the other app, which should make it much easier to determine if a specific source is misbehaving.
