### ISSUE TITLE
Artwork not synchronized with date change

### ISSUE THREAD

**Issue by carterbox** [romannurik/muzei#331]
Since there is one wallpaper per day, the artwork should be changing at midnight. However, my artwork changes are not synced with my local date change, presumably they are changing at midnight UTC because I live on the west coast of North America.

I'm running android 5.1, if that is relevant.

**Comment by ianhanniballake** [comment]
The next artwork for the featured art source is controlled server sid, with [some jitter](https://github.com/romannurik/muzei/blob/master/source-featured-art/src/main/java/com/google/android/apps/muzei/featuredart/FeaturedArtSource.java#L231) to prevent overloading the server.

You're right that usually that is set to midnight UTC as that is when when the [muzei.co Archive](http://muzei.co/archive) and [today's wallpaper webpage](http://muzei.co/today) change over. Right now I think we'd prefer to keep these in sync.

**Comment by carterbox** [comment]
My understanding from what you've said, is that the timing for all the requests to pull the next artwork is randomly and independently chosen on each device in some window around 00:00 UTC.

So, just a suggestion, if you're trying to flatten out your server load anyways, dividing users update schedule according to local time zone would further spread server load out over 4 hours if most of your users are operating in North America. Or if devices could randomly choose a time between local 00:00 and local 05:00 when [most people are sleeping](http://flowingdata.com/2015/11/30/most-common-use-of-time-by-age-and-sex/) it would spread the server load even more (though server load would no longer be uniform and would depend on population density).

I guess your reason for keeping all the updates in sync is that in order to implement the above for the entire world, you would need to:
1. Choose a picture of the day before 00:00 UTC+14:00
2. Adjust code in both your website and app such that it requests the correct image for the device's local time

IMO, this would create a better user experience, but I understand that other issues may have higher priority. Keep up the good work, and thanks for responding so quickly.
