### ISSUE TITLE
Release the minor changes in the API with a minor version increase?

### ISSUE THREAD

**Issue by tasomaniac** [romannurik/muzei#342]
I know that you guys are planning to have much more improvement on the API side. But until then, what about releasing the current state with a minor version increase?

I'm particularly looking into `attribute` field in the `Artwork` class. That would be really handy.

**Comment by ianhanniballake** [comment]
I've done all the cleanup necessary for an API release (in AAR form!) in #353 

Assigning to @romannurik to press the button.

**Comment by tasomaniac** [comment]
Awesome. Thank you

**Comment by ianhanniballake** [comment]
We're going to skip straight to Muzei 3.0's new API.
