### ISSUE TITLE
v2.3 missing in F-Droid Store

### ISSUE THREAD

**Issue by Krawei** [romannurik/muzei#369]
When I take a look in the playstore I notice, that "Muzei's" current version is v2.3. In the F-Droid store the current version is v1.0.1.

What's the reason for the different versions? Is this Github-project still alive?

Kind Regards,

Krawei

**Comment by TheQwerty** [comment]
See issue #204. The maintainers do not want to support a non-Google Play Services version which means they cannot meet F-Droid's [Inclusion Policy](https://f-droid.org/wiki/page/Inclusion_Policy).
