### ISSUE TITLE
[Feature Request] Native Tasker Art Source Support

### ISSUE THREAD

**Issue by xd1936** [romannurik/muzei#376]
Having Tasker "Go To Next Artwork" Plugin support in Beta 4 (d1c7b1f894e5e141d62984de6d903a808d1ff96d) is fantastic. It would be great if we could have full Tasker-as-an-Art-Source built-in natively!

Perhaps Muzei could check to see if Tasker is installed, and if it is, show Tasker as an art source option. Then you could have your Tasker task send over Image(s), Title(s), Subtitle(s), View URL(s), and the number of seconds you want Muzei to wait before going to the next image.

**Comment by ianhanniballake** [comment]
This is a feature request for Tasker: they'd need to add a Muzei Art Source to their app.
