### ISSUE TITLE
per-page multi wallpaper

### ISSUE THREAD

**Issue by eadmaster** [romannurik/muzei#378]
Is it possible to apply a different wallpaper on different home screen pages?
(like [multipicture live wallpaper](https://play.google.com/store/apps/details?id=org.tamanegi.wallpaper.multipicture))

**Comment by ianhanniballake** [comment]
Thanks for the feature request. Unfortunately, there's no Android API for live wallpapers like Muzei to determine the number/size/changing of pages so this type of feature will most definitely not work consistently across all launchers, sorry.
