### ISSUE TITLE
Android O: Update API to work well with Background Service Limitations

### ISSUE THREAD

**Issue by ianhanniballake** [romannurik/muzei#399]
The current `MuzeiArtSource` API is `startService` based. It should be redesigned to work better with [Background Service Limitations](https://developer.android.com/preview/features/background.html#services) as well as Doze and App Standby.

**Comment by cbeyls** [comment]
For reference you can take a look at [SeriesGuide API v2](https://seriesgui.de/api/). Initially, it was using the same API model as Muzei in v1.

**Comment by ianhanniballake** [comment]
We'll be going a different direction for the v2 API, but thanks for the example.

**Comment by ianhanniballake** [comment]
The [Muzei 3.0 and the new API](https://medium.com/@ianhlake/muzei-3-0-and-the-new-api-4fd3d6133db6) is now available in alpha form and works well with Background Service Limitations, Doze, and App Standby.
