### ISSUE TITLE
Not using native resolution for wallpaper

### ISSUE THREAD

**Issue by Theobald93** [romannurik/muzei#409]
Hi,
i have a 720x1280 screen and 720x1280 wallpapers on the local storage.
Why does the app zoom into the picture instead of taking the whole picture for wallpaper?
The preview works well.

Android 7.1.2
Muzei 2.3

**Comment by Theobald93** [comment]
I found this old request for fit all images of any resolution in screen. Https://github.com/romannurik/muzei/issues/196

**Comment by ianhanniballake** [comment]
That's a different issue, related to showing the artwork within the app (rather than how it is displayed as the wallpaper)

**Comment by ankithjoseph** [comment]
@Theobald93 same issue here... Did you find any work around??!

**Comment by Theobald93** [comment]
@ankithjoseph: Nope sorry, i use another app(s) to use my local wallpapers with native resolution.

**Comment by ianhanniballake** [comment]
Exact resolution images will be fully supported in Muzei 2.5.0 (starting in Beta 5 when it is released).
