### ISSUE TITLE
7.1.2+ Storage permissions problem

### ISSUE THREAD

**Issue by joelclaudio** [romannurik/muzei#437]
I am implementing a muzei plugin that creates and stores images locally inside Android/data/com.example.myplugin/files/images/ . It works perfectly on 5.0+ android versions but from 7.1.2+ onwards, while running the newest version of Muzei it doesn't have access to the Myplugin generated images anymore

With the last iteration of Muzei I've found out that the Muzei doesn't has permissions by default to the storage which gave me 2 options:

1) I created something similar to the setupActivity - GallerySetupActivity to check and give permissions but this unfortunately only gave permissions to Myplugin app, keeping Muzei with the Storage permission disabled

2) I created a FileProvider as per the android documentation ( on https://developer.android.com/training/secure-file-sharing/setup-sharing.html ) but it doesn't work because it's not exported=false:

```java
6-27 00:37:25.268 1580-1860/? W/ActivityManager: Permission Denial: opening provider android.support.v4.content.FileProvider from ProcessRecord{93cfe6b 19711:net.nurik.roman.muzei/u0a86} (pid=19711, uid=10086) that is not exported from UID 10091
06-27 00:37:25.269 19711-20218/? E/DownloadArtworkTask: Error downloading artwork
                                                        java.io.FileNotFoundException: No access to content://com.example.myplugin.fileprovider/mypluginimages/577fdc4c-30ac-4d71-931c-5c1068e8b46a.png: java.lang.SecurityException: Permission Denial: opening provider android.support.v4.content.FileProvider from ProcessRecord{93cfe6b 19711:net.nurik.roman.muzei/u0a86} (pid=19711, uid=10086) that is not exported from UID 10091
```

If I try to put the FileProvider with exported=true it doesn't work as well failing with the expected error of:

```java
Unable to get provider android.support.v4.content.FileProvider: java.lang.SecurityException: Provider must not be exported
```

My code for the point 2 of exported=false:
```java
var intent = Intent(Intent.ACTION_VIEW, Uri.parse(bg.uri)).addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
        publishArtwork(Artwork.Builder()
                .imageUri(Uri.parse(bg.uri))
                .title(bg.title)
                .byline(bg.byLine)
                .viewIntent(intent)
                .build())
```

Where bg.uri was saved to a Realm database like this:

```java
addBackground(imageName, "Unknown Myplugin, c. 1984", Date(), FileProvider.getUriForFile( context, "com.example.myplugin.fileprovider", file).toString(), forGallery)
```

Does anybody has a suggestion for sharing files between my plugin and Muzei or this is something that is not possible from this version onwards?

**Comment by ianhanniballake** [comment]
You can use alternate libraries such as [StreamProvider](https://github.com/commonsguy/cwac-provider) which provides a similar API as `FileProvider` but does support `exported="true"`.

In the [upcoming API structure](https://medium.com/@ianhlake/the-muzei-plugin-api-and-androids-evolution-9b9979265cfb), loading artwork will be done by your app, rather than by Muzei. This will allow you to use local files directly.

**Comment by joelclaudio** [comment]
Thanks for your help, Ian. Using StreamProvider I was able to make this work as I intended. 

Once again, thanks to you and all of the contributors of Muzei.
I'll close this issue.
