### ISSUE TITLE
Update forces endless reboot

### ISSUE THREAD

**Issue by jirka-grunt** [romannurik/muzei#449]
Version from July 16 causes immediate reboot after update from Google Play. Long boot with "optimizing apps" process is followed by the same subsequent reboot.

Only solution is remove application using adb shell from recovery.

Affected phone is Google Galaxy Nexus with Cyanogenmod 12.1-20160719.

**Comment by ianhanniballake** [comment]
Crashes in your operating system should be reported to the operating system maintainers. Without a stack trace or other information to help debug issues, there's nothing to do on Muzei's side.

**Comment by Avapro** [comment]
A similar problem CyanigenMod 12.1 Samsung Galaxy S3 Neo
