### ISSUE TITLE
Application unexpectedly turns off from time to time.

### ISSUE THREAD

**Issue by IwoHerka** [romannurik/muzei#455]
Hi. As mentioned in the title, Muzei just turns off from time to time. No crashing or otherwise strange behaviour.

Phone: Nexus 5X
System: 7.1.2

**Comment by ianhanniballake** [comment]
Feel free to [take a bug report](https://tamingthedroid.com/take-bug-report) immediately after seeing this issue and send it to support@muzei.co - as it is, this is not enough information to be actionable or reproducible.
