### ISSUE TITLE
Android Wear 2.0 background issue

### ISSUE THREAD

**Issue by theofficialknightvision** [romannurik/muzei#460]
I've noticed that when I have Muzei set up on my phone and watch, the wallpaper will change on my phone but not on the watch (I'm using the Asus Zenwatch 3). I've tried clearing the app data on the watch app, rebooting the watch, rebooting the phone as well as uninstalling and reinstalling the app on the watch all to no avail. Is there any way to fix this?

**Comment by ianhanniballake** [comment]
I haven't seen this issue before. Can you send a bug report from your phone and watch to support@muzei.co immediately after you notice the wallpaper not changing on your watch? Please include what plugin you are using with Muzei.
