### ISSUE TITLE
Ugly blank space for wide artwork

### ISSUE THREAD

**Issue by maheshgaya** [romannurik/muzei#484]
Wide artwork with short height produces an ugly blank black space. Is there a way that this can be stretched or that the artwork can be skipped for a better one?

<img src="https://user-images.githubusercontent.com/11140545/30676622-944d8556-9e4c-11e7-87b5-fd2c2681303b.png" alt="screenshot_20170920-212657" width="50%">

<img src="https://user-images.githubusercontent.com/11140545/30676623-9581badc-9e4c-11e7-97fd-65e38d13d1d2.png" alt="screenshot_20170920-212641" width="50%">

**Comment by ianhanniballake** [comment]
It doesn't actually have a short height, the artwork just failed to load entirely (if you tap on the title, you'll see the full artwork on the wikiart website). Can you force stop Muzei, re-activate Muzei, and then [send a bug report](https://tamingthedroid.com/take-bug-report) to support@muzei.co?

Currently, there's no way to force Muzei to reload a piece of artwork from the network, so if force stopping & activating it again doesn't fix it, you'll need to wait ~a day for the next artwork or have to Clear Data.

I'll keep this in mind when building the [new plugin API](https://medium.com/@ianhlake/the-muzei-plugin-api-and-androids-evolution-9b9979265cfb).
