### ISSUE TITLE
Feature Request: freeze wallpaper option

### ISSUE THREAD

**Issue by mviesel** [romannurik/muzei#485]
Sometimes a wallpaper comes up that I really like and want to keep it for awhile, so I'd like to be able to suspend the app from switching wallpapers. I've tried extending the interval in that case, but then it immediately switches to a new wallpaper and applies the new interval to that one. Also, I don't see any way to go back to the previous wallpaper, so a "back" button would also be a nice option.

**Comment by ianhanniballake** [comment]
Thanks, I think will be covered in #413 (to stick with just a single image) and #486 (to browse older artwork and select one of them).
