### ISSUE TITLE
AlarmManager.set() may be delayed

### ISSUE THREAD

**Issue by frankFic** [romannurik/muzei#492]
Hi,
I found that AlarmManager.set() is used to schedule retry download in TaskQueueService.
Just for your information, the alarms registered by this API could be batched by the system from API 19 ([doc](https://developer.android.com/reference/android/app/AlarmManager.html#set(int,%20long,%20android.app.PendingIntent))). The exact triggering time for the tasks could vary.

**Comment by ianhanniballake** [comment]
Yes, that is working as intended. Exact timing for retries is not necessary.
