### ISSUE TITLE
Use API 27's WallpaperColors API

### ISSUE THREAD

**Issue by ianhanniballake** [romannurik/muzei#494]
Muzei should override [onComputeColors](https://developer.android.com/reference/android/service/wallpaper/WallpaperService.Engine.html#onComputeColors%28%29) to let the system know the colors in the current wallpaper, calling [notifyColorsChanged()](https://developer.android.com/reference/android/service/wallpaper/WallpaperService.Engine.html#notifyColorsChanged()) when the artwork changes.

**Comment by ianhanniballake** [comment]
Fixed in #500

**Comment by geekycow** [comment]
> Fixed in [#500](https://github.com/muzei/muzei/pull/500)

Unfortunately, apparently not.  😞


*System Material You colours **ARE** successfully fully updated-*
- On Muzei activation
- On system boot
- And similar restarting of the app

*But colours **ARE NOT** properly updated-*
- On automatic wallpaper change
- On manual wallpaper selection
- On "next wallpaper" gesture


*Confirmed on-*
- Nokia 5.3 running stock Android 12
- Nokia X30 Pro running stock Android 14

**Note: Both are Google Android One certified**

**Comment by ianhanniballake** [comment]
As explained in #764, it is expected that the system only changes the system colors after you turn your screen off and then back on again.
