### ISSUE TITLE
Incomplete download of artwork

### ISSUE THREAD

**Issue by carterbox** [romannurik/muzei#507]
I been experiencing incomplete display of artwork as shown below. Today is the second time it has happened. The previous time it occurred was October 10.
At first, I thought this was related to #53, but the black bar is persistent. Also, screen rotation is disabled on my device. Additionally, I tried changing the blur, grey level, etc with no results. Only deleting the muzei data and cache causes the image to appear fully.
I suspect that the image is not being downloaded completely before it is displayed. If that is the case, perhaps checking the validity of the image with some kind of hash could be used to detect incomplete download. 
 
![screenshot_20171010-140131](https://user-images.githubusercontent.com/9604511/32811766-508b5aca-c956-11e7-8697-80eaccfaac40.png) ![screenshot_20171114-153957](https://user-images.githubusercontent.com/9604511/32811767-5175234e-c956-11e7-9053-d5e870e1a666.png)

**Comment by ianhanniballake** [comment]
Dup of #484 - detecting incomplete downloads will be done as part of the new API work.
