### ISSUE TITLE
Change notification bar to dark mode when night mode is ON

### ISSUE THREAD

**Issue by riyaz** [romannurik/muzei#508]
Any plans to implement dark notification bar when night mode is ON, it would be a nice addition.

Done a hacky implementation here https://github.com/riyaz/muzei/commit/be6652d351d52125aa5d26ab00c8a2d80d16cc9d

**Comment by ianhanniballake** [comment]
No, Muzei will continue to report the true wallpaper color. Please [file an Android feature request](https://issuetracker.google.com/issues/new?component=192706) if you'd like the System UI to take night mode into consideration.
