### ISSUE TITLE
Blur effect bug in the main Activity

### ISSUE THREAD

**Issue by tasomaniac** [romannurik/muzei#513]
Steps to reproduce

Open the main Activity to see the wallpaper in full
Lock the screen
Unlock again 
The wallpaper gets blurred and stuck in that state.

After this it cannot be scrolled and double click does not work to unblur it.

**Comment by ianhanniballake** [comment]
Interestingly, I can't seem to reproduce this on the current master. Please reopen it if you see it crop up in the future (preferably in a [beta build](https://play.google.com/apps/testing/net.nurik.roman.muzei) so that it can be fixed before going to production).

**Comment by tasomaniac** [comment]
I can reproduce it with the latest beta. When is the next beta release from Master?

**Comment by ianhanniballake** [comment]
[Muzei 2.5 Beta 1](https://plus.google.com/+IanLake/posts/8Q25TrQXciD) is out now!

**Comment by maheshgaya** [comment]
I got that too! But then if you switch to the Sources tab and back to Muzei, the blur goes away

**Comment by tasomaniac** [comment]
Could it be device dependant? I just updated to latest beta and the bug is still here. I have OnePlus 5 with Oreo.

**Comment by ianhanniballake** [comment]
I'm not having any luck reproducing this or figuring out how this is happening. Could you try (in this order):
1. Restarting your device
2. Switching to a different wallpaper, then re-activating Muzei

**Comment by tasomaniac** [comment]
Did both, still there. I will check with a different  device
