### ISSUE TITLE
Wallpapers from gallery functionality does not work

### ISSUE THREAD

**Issue by FraMecca** [romannurik/muzei#514]
When I try to setup a wallpaper from gallery using muzei it does not work.
I noticed that muzei has no permission to read from storage. Is this the issue?

**Comment by ianhanniballake** [comment]
It is up to the sending app to give Muzei the correct temporary permission to make a copy of the image - this is how Google Photos works, for instance. Please report the issue to the maker of the gallery app you are using. You can refer them to the published [guidance on sharing files and images](https://medium.com/google-developers/sharing-content-between-android-apps-2e6db9d1368b#ad2c).

**Comment by FraMecca** [comment]
Thank you, for both the reply and muzei
