### ISSUE TITLE
Muzei keeps switching Sources

### ISSUE THREAD

**Issue by pwd-github** [romannurik/muzei#519]
No matter how many times I switch the source to Backdrops, within a day it'll switch back to Featured Art.

**Comment by ianhanniballake** [comment]
Muzei switches back to the default source only if the source crashes when Muzei sends it an action (such as the 'Next Artwork') or the source disables itself. That is working as intended. I'd strongly suggest contacting Backdrops.

If you want to [send a bug report](https://developer.android.com/studio/debug/bug-report.html#bugreportdevice) to support@muzei.co taken as soon as you can after it switches back to the Featured Art, we can confirm exactly what happened.
