### ISSUE TITLE
Muzei just stops working with third party apps

### ISSUE THREAD

**Issue by chrisvella** [romannurik/muzei#521]
I have a highly annoying bug to report. After a number of rotations (I have Muzei on a 1 hour - 30 minute rotation period) it fails to update anymore. This will usually happen after a couple of days. I have experienced it with two third party apps; Minima and Backdrops so I am certain the problem is with Muzei.

Nothing I do will fix the problem except uninstalling and reinstalling Muzei and the third party apps. I have tried restarting the phone, changing sources, uninstalling-reinstalling the third party apps (that just breaks any connection with Muzei), and turning off battery optimisation.

I love the app but its unusable with this problem. I am using Lineage OS 14.

Thanks

**Comment by chrisvella** [comment]
Possibly related to [190](https://github.com/romannurik/muzei/issues/190)

**Comment by ianhanniballake** [comment]
Yep, you must disable battery optimizations on the extensions you are using due to how the Muzei API works. [App Standby](https://developer.android.com/training/monitoring-device-state/doze-standby.html#understand_app_standby) disables network access after ~3 days, which seems like exactly what you are experiencing.

**Comment by chrisvella** [comment]
@ianhanniballake as stated in the original issue I have tried playing with battery optimisations and I still have these issues. I gave up on trying to get this to work so I am now using the built in image library source.

**Comment by ianhanniballake** [comment]
The important part is disabling battery optimizations not on Muzei, but on the source you are using. This has consistently worked in testing both locally and with other users. If you've found this not to be the case for you and you've
1) Disabled battery optimizations on your source of choice (and, if they talk to any sources, sources they talk to)
2) Waited the requisite 3 days where App Standby would have turned on without opening the source's settings activity or other UI (which resets the 3 day time period)
3) Have artwork that fails to load

Then please [send a bug report](https://tamingthedroid.com/take-bug-report) to support@muzei.co and I can take a look. Of course, the new API is being designed specifically to not have this issue, so it will eventually solve itself.

**Comment by chrisvella** [comment]
Okay no worries thanks for the info Ian
