### ISSUE TITLE
Rotation interval changes

### ISSUE THREAD

**Issue by chrisvella** [romannurik/muzei#524]
Could you please add a 30 minute interval for rotation of Muzei wallpapers or alternatively a way for the user to more specifically define the period?
I notice two commits were made here: [47](https://github.com/romannurik/muzei/pull/47) and [48](https://github.com/romannurik/muzei/pull/48). They both seem to have been rejected. I really want this feature as I use Muzei with Android wear and 1 hour is too slow.

Cheers,

Chris

**Comment by ianhanniballake** [comment]
Muzei 3.0 introduces a centralized Auto Advance schedule for sources that are built with the new API with intervals as low as every 15 minutes.

The included 'My Photos' source will be moved to the new API before 3.0 hits production.
