### ISSUE TITLE
Question: possible to set animated GIF/WEBP or videos on muzei?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [romannurik/muzei#529]
As the title says...
I would like to know if it's possible to set animated GIF/WEBP or even a video file (WEBM, for example)
If not, what would it take for a live wallpaper to do it?
Does it have to be in a GLWallpaperService with GLEngine? 
Or can it be from a normal WallpaperService ? 

I also wonder why it was chosen to have a GLWallpaperService with GLEngine here, if all that's done is to show an image... Is it for the high quality effects?
Can't those be done using Renderscript, and just use the output image to be shown?

**Comment by ianhanniballake** [comment]
This isn't something Muzei has plans to support.

**Comment by ianhanniballake** [comment]
`MuzeiBlurRenderer` and `GLPicture` were built on OpenGL, precomputing textures for the tiled pieces of the wallpaper images (which can, in their entirety, would often be larger than could fit in memory as a single piece), hence the use of `GLWallpaperService`.

I'm sure you could do it many different ways either with or without the use of OpenGL, but this isn't the place to ask for help for your own project. Best of luck!

**Comment by AndroidDeveloperLB** [comment]
So you load parts of the image, one after another, and send each to OpenGL as texture, to help vs OOM ?
What if you had to make this app again, but this time only from Android 8.0 ?
As I've noticed, Bitmaps gets stored on native memory of the device, and not on the heap, so you have more freedom there...
Do you know where I could start with GLWallpaperService ? As I've noticed, its code is about 6 years old. It doesn't even get to build nicely with Android Studio...

**Comment by romannurik** [comment]
FWIW using GL is necessary to get hardware accelerated rendering in a wallpaper (i.e. canvases can't be hardware accelerated in a wallpaper)

**Comment by AndroidDeveloperLB** [comment]
So it's for the smoother experience when scrolling?
If the image was static, though, there wouldn't be a need for this, no?
Why didn't Google make the canvas there to be hardware accelerated? Makes sense to do it, no? After all, it's graphics that will be shown there...
