### ISSUE TITLE
Black box on screen rotations

### ISSUE THREAD

**Issue by sjparkinson** [romannurik/muzei#53]
I sometimes find a black section appear briefly in the lower portion of my phones wallpaper, during screen rotations.

This frequently happens after turning the screen back on, and also happens after exiting some apps.

After about a second it fixes itself.

The easiest way to reproduce this I found was as follows:
1. Hold the phone landscape
2. Open the camera app (screen then rotates to landscape)
3. Press the home button (another rotation back to portrait, with a black section in the wallpaper briefly appearing)

It's only a minor thing, but not ideal. I'd like to track down the cause of the delay if possible.

**Comment by kappakappakappa** [comment]
So I've encountered the same rendering bug but with .png files. It also doesn't correct itself after any amount of time.

wallpaper as .jpg:
![ggggggg](https://cloud.githubusercontent.com/assets/11600214/6770514/14354c62-d105-11e4-8e9d-426ca8ff07c6.png)


same wallpaper, but as .png
![sfsdfsfsdfdfsdfsdfdssd](https://cloud.githubusercontent.com/assets/11600214/6770513/1434204e-d105-11e4-8f8d-57d0d9360e97.png)

**Comment by foobarth** [comment]
+1 - that's happening for me as well using the Muzei Music plugin, but i think the source doesn't matter. Also, it does not correct itself after rotation, only after applying some filters (which i do not want). So it's an issue with unprocessed images.

![screenshot_2015-08-19-07-25-33](https://cloud.githubusercontent.com/assets/288728/9377580/b14a0b56-471a-11e5-8c62-16fef45e8307.png)
![screenshot_2015-08-19-07-26-42](https://cloud.githubusercontent.com/assets/288728/9377582/b14bbaa0-471a-11e5-913d-4f91acb5e094.png)
![screenshot_2015-08-19-07-26-50](https://cloud.githubusercontent.com/assets/288728/9377581/b14b7ee6-471a-11e5-80bd-8498081be095.png)

**Comment by redmanit** [comment]
I currently stop using Muzei because of this bug. Please take a look at it.

**Comment by romannurik** [comment]
If the black bars stay after rotation it's a different bug than what's described by the OP. Persistent black bars are caused by art sources using interlaced (or was it non-interlaced?) PNGs. This is an Android bug, so not much we can do about it except not use those kinds of PNGs in art sources.

**Comment by tjallingt** [comment]
I have the same issue, i sort of fixed it by enabling the grey filter at about 10% which makes the black box dissappear most of the times.

**Comment by ianhanniballake** [comment]
Muzei 2.6.0 completely redid the logic for loading artwork, now using the most reliable Android API we have available. If you continue to run into issues like this, please send the exact image to support@muzei.co along with what device and Android version you're using.
