### ISSUE TITLE
Question: is it possible to scroll in the photo, while showing the live wallpaper?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [romannurik/muzei#530]
Not all photos have the exact same resolution as the device, after all...

**Comment by ianhanniballake** [comment]
Images with a larger width will scroll, just as they always have.

**Comment by ianhanniballake** [comment]
It works in Pixel Launcher and in Action Launcher. I'd suggest contacting Nova Launcher - they can contact us at support@muzei.co if needed.

**Comment by AndroidDeveloperLB** [comment]
OK I've sent them about it, but I think you should contact them too, because Nova Launcher is far more popular (at least in terms of total downloads) than Muzei :
https://play.google.com/store/apps/details?id=net.nurik.roman.muzei&hl=en
https://play.google.com/store/apps/details?id=com.teslacoilsw.launcher&hl=en

And, since other live wallpapers do work with scrolling of content and touch events, I think it's Muzei that should be fixed.

**Comment by ianhanniballake** [comment]
FWIW, a fresh install of Nova Launcher has wallpaper scrolling working for me with the current Featured Art so there doesn't appear to be anything to do on Muzei's end.

**Comment by AndroidDeveloperLB** [comment]
Maybe it's because I've set there gestures?
But the gestures are for swipe-up, swipe-down and double-tap.
There isn't one for left/right, even if I wanted.

**Comment by AndroidDeveloperLB** [comment]
And it doesn't explain how come other live wallpaper do scroll.
