### ISSUE TITLE
Make Muzei work on Chrome OS

### ISSUE THREAD

**Issue by diskostu** [romannurik/muzei#532]
I really love Muzei on my Android phone and it is really an app I can't live without. :-)
I do not know if this is technically possible, but it would be great if we could have Muzei work on Chrome OS.

**Comment by ianhanniballake** [comment]
Unfortunately, Chrome OS devices do not yet allow live wallpapers like Muzei as of yet - I'd recommend sending feedback from your Chromebook asking them to allow live wallpapers from Android apps such as Muzei as we'd love to support them as soon as we can.
