### ISSUE TITLE
Bug on Android P Beta (DP2) : colors of wallpaper don't affect anything anymore

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [romannurik/muzei#533]
Suppose you take a fully black background via the app.
On Android 8.1 and even on Android P DP1, this would affect the notification drawer, to make it black too.

Now on Android P Beta (DP2), it doesn't.

According to my tests, this happens on all third party live wallpapers, but not on the built in ones.

Because of the above, I believe this is a bug on the OS. However, if it's not, please let me know why this occurs and how to fix it.
I've reported about this issue here too :
https://issuetracker.google.com/issues/80029770

**Comment by ianhanniballake** [comment]
This would be a regression on the OS side, not anything that Muzei can control. Thanks for following up on it on the issue tracker!

**Comment by AndroidDeveloperLB** [comment]
@ianhanniballake Exactly what I was thinking, but I can't convince them this is what's going on. Each time I present them the issue, they misunderstand it differently:
https://issuetracker.google.com/issues/79665215
https://issuetracker.google.com/issues/79950962
https://issuetracker.google.com/issues/80029770

I'm very sure it's because of the OS.
The reasons:
1. Worked fine (meaning the API actually does something) on Android 8.1 and P DP1.
2. Works fine for built in live wallpapers and normal dark wallpapers
3. Doesn't work for any third party live wallpaper, including Muzei.
4. Moving Muzei to be a system app doesn't help.

So something is definitely wrong here, and I really hope it gets fixed.

Can you please please please tell them this is a bug that should be fixed?

**Comment by AndroidDeveloperLB** [comment]
BTW, I've reported a lot of issues on the issue-tracker. I always check it out well before posting.
But this is a 100% bug so I'm not giving up.

**Comment by AndroidDeveloperLB** [comment]
@ianhanniballake It's worse than regression:
It's inconsistent and "discriminating" because of giving only built in apps true usage of the API, as when third party apps use the API, it doesn't do anything at all.
Can you please inform them ? I've done my best 3 times already and I still keep being misunderstood.

**Comment by AndroidDeveloperLB** [comment]
@ianhanniballake My hopes about this fix seem to have some fruits : 
https://issuetracker.google.com/issues/80029770#comment8

> The development team has fixed the issue that you have reported and it will be available in a future build.

I don't know if it's you who told them about it, or they finally listened to me. Thank you anyway.
