### ISSUE TITLE
Update problem

### ISSUE THREAD

**Issue by fausto437** [romannurik/muzei#534]
In my device Moto G5 is not updating the wallpaper since a couple weeks ago. There is a way to reset the app?

**Comment by ianhanniballake** [comment]
This should be fixed in Muzei 2.5.2 (released to 100% of production just today). If you're still having issues, clearing data on Muzei will fix things entirely - would be nice to know if 2.5.2 fixes things for you though.

**Comment by appwheredescf** [comment]
it's working great, thank you.
