### ISSUE TITLE
Muzei App crashes when I rotate my phone in landscape mode.

### ISSUE THREAD

**Issue by pzdawood** [romannurik/muzei#536]
### Actual behaviour
When I open the muzei app and click on activate option. After that I click on settings option and change orientation and market option . After that I rotate my phone in landscape mode app suddenly crashes.
### How to reproduce
* Download the muzei app from F-driod.
* Install this app.
* Open the muzei app.
* Click on settings option.
* Change orientation and market option.
* Then rotate your phone in landscape mode app suddenly crashes.
* Browser:muzei.
* Version: 2.4.0
* Operating system: 7.1.2
### Recording of the bug
https://youtu.be/jYwVc26hqK4

**Comment by ianhanniballake** [comment]
Muzei 2.4.0 is over 6 months old and 3 releases out of date and f-droid is not a supported app store.

If you can reproduce it using Muzei 2.5.2 (the latest from the Google Play Store), please send a bug report to support@muzei.co
