### ISSUE TITLE
Increased power consumption

### ISSUE THREAD

**Issue by kuronecoruri** [romannurik/muzei#543]
My version is 2.6.0 beta2. Recently muzei uses about 10% power, can you fix it?

**Comment by ianhanniballake** [comment]
If you could send a bug report to support@muzei.co from your device, we can look at what is consuming power.

**Comment by ianhanniballake** [comment]
I've been unable to reproduce this. If you see this again after upgrading to Muzei 2.6.1 (out now!), please do send us a bug report right after you notice it.
