### ISSUE TITLE
Only get a part of the image when using the pics from reddit add-on 

### ISSUE THREAD

**Issue by TheEdgeOfRage** [romannurik/muzei#544]
I'm using the pics from reddit add-on to download wallpapers and until the last update Had no issues with it. Now 90% of the time it only downloads a part of the image like this.

![https://imgur.com/eS8uWsn](https://imgur.com/eS8uWsn)

Sometimes it gets only a few rows and sometimes the whole image, but far more often the former.

I'm not sure whether this is muzei's fault or the add-on's, but it only started happening after the muzei update, so that why I'm opening the issue here.

I use non-stock android 8.1 (Resurrection Remix) and version 2.6.0 of muzei. If you need any additional information please let me know.

**Comment by ianhanniballake** [comment]
If you can share the original images that the reddit plugin is attempting to display with support@muzei.co, I can certainly try to reproduce the issue.

**Comment by TheEdgeOfRage** [comment]
It's trying to pull images currently hot on the subreddits that I chose. Which in my case are [EarthPorn](https://reddit.com/r/EarthPorn) and [analog](https://reddit.com/r/analog). It's pretty much random from which sub it's going to pull the image, though I presume it has to do with votes.

Either way the sub doesn't matter as no image will load. Is there still need to send an example then? Since it does change all the time.

**Comment by ianhanniballake** [comment]
I cannot reproduce this on any of the devices I have with the images I've tried. Having the exact image that fails to load on your device would allow me to determine whether it is truly a device specific issue or something that can be reproduced and fixed.

**Comment by TheEdgeOfRage** [comment]
Alright, I tracked down the issue. Whenever it's trying to load images that are themselves hosted on reddit it won't load the whole image. So any image from https://i.redditmedia.com. When theres a post that links to imgur it loads just fine, which explains why some were working. Here's a list of images that you can try to reproduce the issue with, I will also send this to the support@muzei.co email:

Not working:

- https://i.redd.it/0jd5xdoo8p711.jpg
- https://i.redd.it/8xhstifvwp711.jpg
- https://i.redd.it/togwo424vr711.jpg
- https://i.redd.it/inj7rt45lr711.jpg

Working:

https://imgur.com/Sl02fbd
https://i.imgur.com/aUU3rYV.jpg
https://i.imgur.com/o7kAgTi.jpg

**Comment by TheEdgeOfRage** [comment]
For reference, if anybody has the same problem, you can rotate the phone if the image doesn't decode correctly and it should work when you turn it right up. It's a workaround, not a solution, but the problem is in the Android API not in muzei.
