### ISSUE TITLE
New Source For Paintings

### ISSUE THREAD

**Issue by TGNYC** [romannurik/muzei#546]
Hey, I don't know where you get the sources for the classical art that comes default with the app, but the Van Gogh Museum in the Netherlands have recently digitized thousands of Van Gogh's art [here](https://www.vangoghmuseum.nl/en/search/collection?q=&artist=Vincent%20van%20Gogh&pagesize=105), and I thought you might want to add them to your collection.

Cheers!

**Comment by ianhanniballake** [comment]
Thanks for letting us know. Muzei's Featured Art is sourced primarily from [wikiarg.org](www.wikiarg.org)
