### ISSUE TITLE
Feature Request: add option to disable blur on main homescreen page 

### ISSUE THREAD

**Issue by dariusz-goc** [romannurik/muzei#548]
Option to disable blur on main homescreen page or page(s) of user's choice. Perfect for when you have clean home page for looking at your wallpaper and semi-transparent widgets on subsequent pages for getting things done.

**Comment by ianhanniballake** [comment]
Unfortunately, there's no API for a launcher to tell Muzei what page it is on.

**Comment by dariusz-goc** [comment]
But the live wallpaper is receiving the scrolling info (for wallpaper position adjustment), isn't that sufficient?

**Comment by ianhanniballake** [comment]
No, every launcher acts slightly differently in the offsets that they send to Muzei. Some are well behaved in that they start at 0 offset and translate a fixed amount over, but others place the live wallpaper differently where we never get to a 0 offset (say, if they try to center the wallpaper but still parallax).

Until there's a consistent API provided by the framework, this will always be a bit too fragile to consider given the wide array of launchers available.
