### ISSUE TITLE
Decouple home screen and lock screen effects

### ISSUE THREAD

**Issue by ianhanniballake** [romannurik/muzei#549]
Allow users to have totally independent effects between the lock screen and home screen, replacing the 'Apply blur on lockscreen' checkbox.

**Comment by AndroidDeveloperLB** [comment]
@ianhanniballake Is it this feature:

![image](https://user-images.githubusercontent.com/5357526/172115352-78ed8ce9-3ee1-4905-8fa0-be03e78d53e7.png)

If so, was it done using a callback, or using polling of a query (whether it's lock screen or not) ?
I've searched about callbacks and couldn't find it. This is why I requested it on the issue tracker:
https://issuetracker.google.com/issues/205726875

**Comment by ianhanniballake** [comment]
@AndroidDeveloperLB - this issue is completely unrelated to the [`LockscreenObserver`](https://github.com/muzei/muzei/blob/912e22b90d2d34d7577ad80249fe046d2044dafd/main/src/main/java/com/google/android/apps/muzei/wallpaper/LockscreenObserver.kt), the key of which is the [`ACTION_USER_PRESENT`](https://developer.android.com/reference/android/content/Intent#ACTION_USER_PRESENT) broadcast introduced in Android 1.5 Cupcake to know when the user unlocks their device.

**Comment by AndroidDeveloperLB** [comment]
@ianhanniballake So you say it's very possible to do it? Why did you write "unrelated" , though? It seems it's very related.
And why if it's just ACTION_USER_PRESENT, does this class also listen to other Intents, such as ACTION_SCREEN_OFF and ACTION_SCREEN_ON  ? 
Is it possible to have a LiveData that is always in sync with the state (turned off, locked, unlocked) ?
