### ISSUE TITLE
Provide Buildable Example Art Source

### ISSUE THREAD

**Issue by xd1936** [romannurik/muzei#552]
[The Unsplash Art Source example code](/romannurik/muzei/tree/master/example-unsplash) is great to have, but it sure would be nice if it was a complete, buildable project in Android Studio. Someone like me who's interested in building my first Android app as a Muzei plugin might have a hard time getting off the ground.

**Comment by ianhanniballake** [comment]
It already is buildable - checkout the Muzei source code, then select `example-unsplash` from the run dropdown.

Swapping out the `implementation project(':muzei-api')` line in the `build.gradle` for the commented out dependency on the `muzei-api` is enough to totally decouple it from the rest of the modules.
