### ISSUE TITLE
Avoid double effects transition when using fingerprint unlock

### ISSUE THREAD

**Issue by ianhanniballake** [romannurik/muzei#554]
When using different effects for the home screen and lock screen, turning off the screen will trigger the change to the lock screen effects. However, because the screen is off, the transition won't run until the screen turns back on.

This leads to a situation where if you use a fingerprint to both turn on the screen and unlock the device, you see a transition to the lock screen effects, then back to the home screen effects instead of immediately seeing the home screen effects.

**Comment by eevleevs** [comment]
Also valid to normal unlock without fingerprint. The transition from home settings to lockscreen settings is just not useful, and becomes a distraction in most cases. Should be removed.

**Comment by Makxik** [comment]
mb about # 686. So why should this be removed?  The transition is too much delayed right now.

**Comment by ianhanniballake** [comment]
We've removed the transition *to* the lock screen effects - Muzei will instantly be on the lock screen effects when you turn your screen on.

**Comment by xcom923** [comment]
wow, thanks for this. I've been "suffering in silence" for a while. I love Muzei but that's one thing that really annoyed me.
