### ISSUE TITLE
API v3: make getLastAddedArtwork() more robust

### ISSUE THREAD

**Issue by cbeyls** [romannurik/muzei#555]
Both in `ProviderContract` and in `MuzeiArtProvider`, the method `getLastAddedArtwork()` returns the last added artwork based on the `DATE_ADDED` column. However when many artworks are added in batch, it's possible that the timestamps of different artworks are identical.

I suggest to rather select the last added artwork based on the `_ID` column instead, which is unique and auto-incremented. Furthermore, since this column is indexed, the query should run faster when there are many artworks.

**Comment by ianhanniballake** [comment]
This fix is now available in the `com.google.android.apps.muzei:muzei-api:3.0.0-alpha02` release.
