### ISSUE TITLE
API v3: Fix autocaching logic

### ISSUE THREAD

**Issue by cbeyls** [romannurik/muzei#556]
While doing tests switching between images of a source providing exactly 6 artworks, I noticed that at most 5 of them are cached at a time, even if `MAX_RECENT_ARTWORK` is set to 100.

It turns out that the `recentArtworkIds` queue may contain duplicates but the code doesn't take that into account.
In `MuzeiArtProvider.java` line 367, when the queue is shrinked to fit the total number of items in the provider, the recent item at the front of the queue is deleted from disk, even if it's also present in another position in the queue. Later, an unnecessary cache miss will occur when trying to load that artwork.

Suggestion: either remove duplicates from the `recentArtworkIds` queue, or use another logic to purge the cache.
One way to remove duplicates in `recentArtworkIds` is to use an `LruCache` or `LinkedHashMap`, which is both a map and a queue, so when a recent item which was already present is retrieved or added, it's simply moved back at the end of the queue.

**Comment by ianhanniballake** [comment]
Thanks for the feedback! Feel free to file additional issues or contact support@muzei.co with any more general feedback about the Muzei 3.0 API.

**Comment by ianhanniballake** [comment]
This fix is now available in the `com.google.android.apps.muzei:muzei-api:3.0.0-alpha02` release.
