### ISSUE TITLE
Getting "This source is disabled" with targetSdkVersion above 25.

### ISSUE THREAD

**Issue by adrianaisemberg** [romannurik/muzei#561]
Since I updated my app (Tapet) to target SDK level 26, I see this message:
![image](https://user-images.githubusercontent.com/857478/44764205-76bab800-ab03-11e8-9cd9-4167e4217155.png)

According to Google, they require 26 as the minimum for newly submitted apps and updates:
https://developer.android.com/distribute/best-practices/develop/target-sdk

Are you planning to update it?

Thanks!

**Comment by ianhanniballake** [comment]
The [Muzei 3.0 API](https://medium.com/@ianhlake/muzei-3-0-and-the-new-api-4fd3d6133db6) is fully compatible with targeting the latest versions of Android, please use that. Note that Muzei 3.0 is currently in alpha right now, so if your app targets API 26, it won't be compatible with the current production version of Muzei. Right now, I'm shooting for releasing Muzei 3.0 to production around the end of September.
