### ISSUE TITLE
Glance wallpaper source

### ISSUE THREAD

**Issue by nasimalam806** [romannurik/muzei#573]
please add a glance wallpaper source

**Comment by ianhanniballake** [comment]
Muzei offers a plugin system that any app, including Glance, can implement. Feel free to send feedback to Glance with a link to the [Muzei 3.0 API blog post](https://medium.com/@ianhlake/muzei-3-0-and-the-new-api-4fd3d6133db6), which has all of the details on how to build a Muzei source into their app. They can contact us at support@muzei.co if they have any questions.
