### ISSUE TITLE
My source changes to default whenever I reboot

### ISSUE THREAD

**Issue by Santi3598** [romannurik/muzei#574]
Hello, I'm having this issue where whenever I reboot my device, my source of choice (myWalls app) changes to the Featured Art one. What's weird about this is that when the device turns back on after the reboot, it shows the wallpaper that was applied before the reboot but after a few seconds it changes to the Van Gogh one, from the Featured Art source.

I tried a few other sources from Wallpaper apps and they all have the same issue. But when I choose Selected Pictures from my gallery, it works just fine after rebooting. My question is, is there anything I can do to make those sources work after a reboot? Or does it depend on the developer of the source? I'm running Android Nougat 7.0.

**Comment by ianhanniballake** [comment]
The only time Muzei changes back to the default source is if your chosen source crashes when Muzei sends it a command (i.e., the `onEnabled` when Muzei attaches to it or a Next Artwork action). If you'd like to send a bug report to support@muzei.co, I can take a look to confirm that is indeed the case.

**Comment by james58899** [comment]
app in external storage?

**Comment by Santi3598** [comment]
Thanks for the help, but I'm now using wallpapers stored in my device instead, so there's nothing to fix now.

I have another question though. The minimum time to change the wallpapers by using stored pictures as a source is 1 hour, is there a way to make it shorter?

**Comment by ianhanniballake** [comment]
If you join [Muzei's open beta](https://play.google.com/apps/testing/net.nurik.roman.muzei), you'll get Muzei 3.0 which allows you to change the Auto Advance interval of sources such as the My Photos source to as low as every 15 minutes.
