### ISSUE TITLE
Play Store rejection caused by exported Provider

### ISSUE THREAD

**Issue by tasomaniac** [romannurik/muzei#577]
An update with 3.0 API integration was rejected by Play Store. The reason was possible SQL injection 😄 

Here are more details from the rejection: https://support.google.com/faqs/answer/7668308

It looks like they don't like exported Providers, the first solution is to use signature level permission which is not possible for Muzei and extensions I believe. The others are just suggestions around how to use SQL to prevent injection. 

Since clients do not really have control over the SQL usage in the provider, it would be good if this can be fixed in Muzei's side.

**Comment by ianhanniballake** [comment]
As per the [Muzei 3.0 blog post](https://medium.com/@ianhlake/muzei-3-0-and-the-new-api-4fd3d6133db6#3b11), you should be using `android:permission=
    "com.google.android.apps.muzei.api.ACCESS_PROVIDER"`

Is there a reason you did not include that line?

**Comment by tasomaniac** [comment]
I already us that. Here is the extension. Its a really simple one: https://github.com/tasomaniac/MuzeiComicsCovers/blob/master/app/src/main/AndroidManifest.xml

The post says that the permission should be signature level. That means apps need to be signed with the same signature. This is of course not possible. 

In summary it says, the provider should either be private or have protection over SQL injection.

**Comment by ianhanniballake** [comment]
I guess their automated scan doesn't pick up that the permission is signature level on Muzei's side. While technically a false positive on their side, it still isn't something you should have to deal with, so we'll fix it on the API side.

**Comment by tasomaniac** [comment]
Could it be false positive on Play Store because Muzei 3 is not fully published yet and they might be checking against version 2. I'm not sure about what they do 🤔 Maybe it will be automatically resolved when it is released. 

Btw, one more info, they published the app. This was a warning and they gave me a deadline until December 😊

**Comment by ianhanniballake** [comment]
`com.google.android.apps.muzei:muzei-api:3.0.0-beta02` is now available with this fix. See the [full release notes](https://github.com/romannurik/muzei/releases/tag/api3.0.0-beta2) and thanks for reporting this issue!

Let me know if you get a similar warning about SQL injection after upgrading to beta2 and I can reopen this issue.
