### ISSUE TITLE
Muzei loop crash

### ISSUE THREAD

**Issue by marcopar** [romannurik/muzei#581]
I was able to write a, probably bugged, Worker that makes Muzei crash.
The bad thing is that, at least in the emulator (google api 26), Muzei crashes, restarts, crashes again.
Always showing the nasty crash popup and continuing to crash after a reboot.

While this is surely caused by my app (still unsure what's wrong), what the user sees is Muzei crashing every few seconds.
I think you should protect the app against badly written sources.

Stack trace attached

[muzei-crashing.txt](https://github.com/romannurik/muzei/files/2453143/muzei-crashing.txt)

**Comment by marcopar** [comment]
The crash was caused by the null persistentUri
I had to uninstall my source to get it stop crashing. Updating my app did not work.
When debugging my source to understand the crash, the debugger never stopped on my code, as if Muzei had cached the bad artwork and was trying to use it again and again.
After reinstalling probably a cleanup of the cache happened(?) and Muzei got the new fixed artwork from my source.

**Comment by ianhanniballake** [comment]
Yeah, I got a notice a quite a few crashes and assumed it was someone working on a source. We'll update Muzei to catch any exceptions and trigger the `onInvalidArtwork` callback, which defaults to deleting the bad artwork, putting you back into a good state after updating your app.
