### ISSUE TITLE
Clear artworks of a source

### ISSUE THREAD

**Issue by redphx** [romannurik/muzei#584]
Let's say I have a source that returns images from any subreddits. Users can change subreddit anytime they want.  
Here is my scenario:  

1. A user gets images from `r/EarthPorn`.
2. Muzei calls `onLoadRequested` and receives 20 artworks.
3. They change to another subreddit.
4. Muzei won't update because it still has 19 artworks in the queue.

API 2 doesn't have this problem because Muzei has to call the source everytime it needs a new artwork. So I think we need a way to clear all artworks of a source. What do you think?

**Comment by redphx** [comment]
Another scenario:  
1. I have a list of artworks inside my app.
2. Muzei stores the artworks.
3. I update my app with a new list of artworks (add & remove some artworks).  

Will old artworks be removed from Muzei? Will Muzei know that it should call `onLoadRequested` again?  

Thank you.

**Comment by ianhanniballake** [comment]
As your `MuzeiArtProvider` is a `ContentProvider`, you can just delete artwork yourself:
```
val contentUri = ProviderContract.Artwork.getContentUri(GALLERY_ART_AUTHORITY)
context.contentResolver.delete(contentUri, null, null)
```
Using any selection criteria you want. For example, you could use the `METADATA` field to store what subreddit the image came from, then delete all artwork that has that particular metadata when the user unselects that subreddit. This is how the 'My Photos' source deletes images when you remove a image from the settings screen (see [here](https://github.com/romannurik/muzei/blob/v3.0.0-rc2/source-gallery/src/main/java/com/google/android/apps/muzei/gallery/ChosenPhotoDao.kt#L253) for a code sample).

As you add or delete artwork, Muzei does keep in sync, removing deleted artwork and calling `onLoadRequested` if it needs to load more artwork.

**Comment by ianhanniballake** [comment]
> Does this mean that in scenerio 2, users have to open my app each time it has a new version, or artworks won't be updated?

Muzei only reads artwork from your `MuzeiArtProvider`, it does not store any artwork itself. You are free to update the artwork in you provide at any time based on whatever triggers you want. If Muzei is currently displaying artwork you've deleted, it will also delete it. If it doesn't have any new artwork, it will call `onLoadRequested()`.

> Also in my example, I want to add & remove artworks in a JSON file, not using code. I don't want to manually track the differences between two versions.

It is up to you to ensure that your `MuzeiArtProvider` has all of the artwork you want Muzei to display. It sounds like the `METADATA` would work great for your use case:
1. Whenever you load artwork, pick a unique value to signify this load (say, `UUID.randomUUID().toString()` if you don't have anything already)
2. Add all of the artwork from your JSON file every time you load, setting the metadata field on every artwork to that unique value.
3. Delete everything without that specific `METADATA` value - this drops any artwork no longer in the JSON file.

**Comment by redphx** [comment]
Thank you.
