### ISSUE TITLE
API documentation has not been updated to v3 yet

### ISSUE THREAD

**Issue by dvdmunckhof** [romannurik/muzei#585]
The documentation referenced in the readme ([api.muzei.co](http://api.muzei.co/), which redirects to the [wiki](https://github.com/romannurik/muzei/wiki/API) has not been updated to v3, and still documents the legacy v2 API.

The [full API reference](http://api.muzei.co/reference) hasn't been updated either.

Additionally, the [changelog](https://github.com/romannurik/muzei/wiki/Changelog) in that same wiki is still at v2.3.

**Comment by ianhanniballake** [comment]
Yep, still trying to figure out what should happen to all of that. You can download the full API reference from the [release page](https://github.com/romannurik/muzei/releases/tag/api3.0.0)

**Comment by ianhanniballake** [comment]
We've updated [api.muzei.co](https://api.muzei.co) to point to the new staged documentation (which has been rebuilt as part of the [Muzei API 3.4.0-alpha01](https://github.com/romannurik/muzei/releases/tag/api3.4.0-alpha1) to be built in Kotlin with dokka).

We're not updating the wiki pages anymore.
