### ISSUE TITLE
Google Plus Community

### ISSUE THREAD

**Issue by yokhoe** [romannurik/muzei#586]
I apologize if this is the wrong venue, but I don't want to recreate my G+ account just for the sake of asking. Feel free to delete this issue if inappropriate.  Where will the Muzei Community go off too when G+ service close down?  Looking through the community posting, I don't think I can find any info mentioning this yet. Thank you for the incredible work and incredible community.

**Comment by ianhanniballake** [comment]
We'll continue to use the G+ community for the next 9 months. No plans for an alternate community after that at the moment. I'll leave this issue open though for updates if anything changes.

**Comment by sarsamurmu** [comment]
Telegram or Discord is Quite a Good Solution. You can Categorise Channels on Discord. Unfortunately, G+ is Closing too soon in April. Take Decision Soon. See You.

**Comment by ianhanniballake** [comment]
With Google+ closing shortly, I wanted to provide an update here on our plans: we won't be offering a new community like experience.

The following forms of communication will be available:
- For announcements and news about Muzei and its API, please follow our [Muzei Publication on Medium](https://medium.com/muzei) or [my profile on Twitter](https://twitter.com/ianhlake)
- For bugs or feature requests, [file an issue here on Github](https://github.com/romannurik/muzei/issues) or contact us directly at [support@muzei.co](mailto:support@muzei.co)

Thanks for your understanding.
