### ISSUE TITLE
only optional download of new wallpaper without WLAN

### ISSUE THREAD

**Issue by tobleu** [romannurik/muzei#59]
Muzei always downloads wallpapers with any Internet connection - even if this is a non-flatrate, non-stable vor slow connection... If this would be restricted to WLAN , this would be fine :-)

**Comment by nyuszika7h** [comment]
:+1: This is definitely needed. I don't want my limited mobile data plan to be consumed by Muzei.

A workaround for now is to select "Muzei" in "Data usage" and enable "Restrict background data".

**Comment by oXidFoX** [comment]
I agree @nyuszika7h , this is needed!

**Comment by ming13** [comment]
@romannurik Is it possible to get any updates / opinions regarding this? I hear users demand it and many extensions are basically implementing it on their own: for example [Hash](https://github.com/flavienlaurent/muzeihash/blob/fe304fba2eb96c39210930f49b7f31573b7d9cab/app/src/main/java/com/flavienlaurent/muzei/hash/Utils.java#L33-L36), [National Geographic](https://github.com/msal/muzei-nationalgeographic/blob/d131f01e35c71cfc43294ac362986afabae9bc38/muzei-nationalgeographic/src/java/de/msal/muzei/nationalgeographic/NationalGeographicArtSource.java#L270-L276). Probably it is better to have this option on the Muzei’s level. Obviously it should affect only auto-update process, not the manual “next wallpaper” action. The traffic issue becomes even more concerning in our world of 4K wallpapers.

**Comment by tasomaniac** [comment]
I think this is really a good option to have. I solve this personally by blocking background mobile connection of the Muzei app and all of its extensions.

**Comment by ming13** [comment]
@ianhanniballake @romannurik Are there any updates on this?

**Comment by ianhanniballake** [comment]
Muzei 3.0 will introduce an 'Auto Advance only on Wi-Fi' option for sources built with the new API.
