### ISSUE TITLE
next artwork doesn't work 

### ISSUE THREAD

**Issue by TBog** [romannurik/muzei#593]
On my S9+ the picture never changes, even if I hit next artwork button.
I tried a couple of different legacy sources, even the default one (reddit)

**Comment by ianhanniballake** [comment]
As per the [Legacy sources blog post](https://medium.com/muzei/muzei-3-0-and-legacy-sources-8261979e2264), you must disable battery optimizations on the app providing the legacy source you are using. Please contact [support@muzei.co](mailto:support@muzei.co) for technical support for Muzei.
