### ISSUE TITLE
Add Align Option

### ISSUE THREAD

**Issue by sarsa2703** [romannurik/muzei#594]
I made an app with wallpapers. I want to support it through many device that's why the wallpapers are large in width. Is it not possible to add a little option to align the Wallpaper to Left, Center and Right? So,the wallpaper's main subject will not get cut.
I don't know if this feature was requested before. Although, Thanks for making app like this.

**Comment by sarsa2703** [comment]
It

**Comment by ianhanniballake** [comment]
Yup, duplicate of #13, #62, and #64
