### ISSUE TITLE
How to advance to the next page of art source

### ISSUE THREAD

**Issue by osrl** [romannurik/muzei#596]
I've been checking Unsplash example and it calls `UnsplashService.popularPhotos()` which returns some results that may change over time. That's perfectly ok with this kind of source. What if we have a source that returns a paginated data. Is it guarantied that `onLoadRequested` will be called after every artwork is consumed? Would it be ok if I write last used page to shared preferences and increase it after every onLoadRequested call? A `page: Int`  parameter would be great instead of `initial: Boolean`

**Comment by ianhanniballake** [comment]
As per the documentation to `onLoadRequested`, it is called when all artwork you've provided to Muzei has been seen by the user. Yes, storing the current page in SharedPreferences would be fine.

**Comment by osrl** [comment]
Thank you very much for the quick response and clarification.
