### ISSUE TITLE
DocumentProvider does not auto refresh on load

### ISSUE THREAD

**Issue by Ethan1983** [romannurik/muzei#597]
Muzei document provider exposes the daily wallpaper. However, when using Files app to look at Muzei document provider, it shows yesterday's and today's wallpaper. Pull down to refresh does remove yesterday's wallpaper.

  However, it would be nice if this is updated automatically when document provider is queried when Files app is started with Muzei as the active provider.

**Comment by ianhanniballake** [comment]
This is working as intended - the Featured Art source does not automatically move forward to the next artwork (it is the regular Auto Advance that moves you to today's wallpaper), so during that time between loading today's wallpaper and actually seeing it as your wallpaper in Muzei, both wallpapers are correctly visible.

The reason why refreshing clears the old artwork is that it triggers the same `onLoadRequested()` that indicates that we're on the latest image.

**Comment by Ethan1983** [comment]
The only side effect i noticed was without auto refresh when using Files app, user could try to share yesterday's wallpaper to other apps and path obtained from fileUri was invalid and file operation fails in the other app.
