### ISSUE TITLE
Gestures not working on Samsung OneUI or Lawnchair Launcher v2 (alpha)

### ISSUE THREAD

**Issue by vonDubenshire** [romannurik/muzei#603]
Hey,

New to the app and love it. Only thing is I can't get the gestures to work.

I know using Nova or my current launcher, Lawnchair, might cause problems because they have gestures in them but I can't get it to work on the regular Samsung launcher, either.

Running Android 9 on a Galaxy S10e.

Any advice? I hope this is an okay place to post.

**Comment by ianhanniballake** [comment]
The double tap gesture is sent by the launcher to Muzei. Unfortunately, there's not anything Muzei can do about launchers not implementing the standard Android API (specifically, if it is the [COMMAND_TAP](https://developer.android.com/reference/android/app/WallpaperManager.html#COMMAND_TAP) action that they need to send to live wallpapers).

Note that the three finger gesture goes through a different path so you might have better luck with that.
