### ISSUE TITLE
Muzei fast switches bug after long lock time period

### ISSUE THREAD

**Issue by atlasyonatan** [romannurik/muzei#609]
I have Muzei set to switch every 15 minutes. I go to sleep and when I unlock my device in the morning Muzei swiftly switches through all supposedly missed switching events.
This is annoying and should not occur.
The switching is also 1 second each for each missed event.

I am using the latest version through the play store (v3.0.2).

**Comment by ianhanniballake** [comment]
What Source are you using?

**Comment by atlasyonatan** [comment]
Source: My Photos

**Comment by ianhanniballake** [comment]
I haven't been able to reproduce this on [Muzei 3.2.0 Alpha 1](https://medium.com/muzei/muzei-live-wallpaper-3-2-0-alpha-1-41090df5b339). If you could update and check to see if this is fixed for you, I'd appreciate it.

If not, please send [take a bug report](https://tamingthedroid.com/take-bug-report) immediately after seeing this and send it to [support@muzei.co](mailto:support@muzei.co) and we can take it from there.
