### ISSUE TITLE
Info about unsupported sources

### ISSUE THREAD

**Issue by tasomaniac** [romannurik/muzei#615]
## Problem

Every time I open sources page, I get the following error. This message does not really mean anything since I don't know what to do really. 

Learn More button takes me to medium article that is more targeted to developers. 

If I'm not a developer, I have nothing. I would maybe want to know about the details about these unsupported sources so that I can uninstall those apps that are not supported anymore. 

What do you think?

## Screenshot

![Screenshot_20190812-224839](https://user-images.githubusercontent.com/763339/62897359-61aa5980-bd53-11e9-9c1d-7a74b20e6152.jpg)

**Comment by ianhanniballake** [comment]
Muzei sends notifications after you upgrade to Muzei 3.2.0 for each unsupported source, telling you exactly what source is no longer supported. I assume you already dismissed those notifications?

**Comment by tasomaniac** [comment]
Hmmm, I haven't seen them unfortunately. 😔

**Comment by ianhanniballake** [comment]
Muzei 3.2.0 Alpha 5 is rolling out now with a fix (the 'Learn More' link in the Snackbar now opens a separate screen with details about all of the Legacy Sources).
