### ISSUE TITLE
High resolution images be compressed very blurry

### ISSUE THREAD

**Issue by onlymash** [romannurik/muzei#616]
You can load image by [subsampling-scale-image-view](https://github.com/davemorrissey/subsampling-scale-image-view)

![20190815011903](https://user-images.githubusercontent.com/5838634/63074628-a5be7980-bf60-11e9-9346-5ec2c2c32a07.jpg)

**Comment by ianhanniballake** [comment]
Can you attach the image itself? We already load the images at the native resolution into GL textures.

**Comment by onlymash** [comment]
@ianhanniballake 
https://anime-pictures.net/pictures/view_post/608689?lang=en

**Comment by onlymash** [comment]
Can the Muzei app dynamically adjust the display area when the image is used as a wallpaper?

**Comment by ianhanniballake** [comment]
Thanks, that really helps. It seems like this is an encoding issue with this particular image - saving the image either as an interlaced PNG or as a JPEG causes the quality to return to normal, with none of the apparent low resolution issues. I see the same low resolution issues when using Google Photos, FWIW, so I don't think there's anything more we can do.

Unfortunately, live wallpapers do not use views to display their images, so Muzei cannot use `subsampling-scale-image-view` for our images (if you're on Muzei 3.2 Alpha, we do use that for multi-window mode, where we don't rely on the live wallpaper to draw the background).

Muzei always centers the image within the space provided by the launcher, filling the available space - many third party launchers offer controls on disabling wallpaper scrolling, which would mean the image would always be centered in your phone's display.
