### ISSUE TITLE
Missing byline leaves empty space

### ISSUE THREAD

**Issue by ming13** [romannurik/muzei#622]
[A screenshot](https://user-images.githubusercontent.com/200401/64092015-9e1e1380-cd5b-11e9-8a0b-73d9a9def65d.png) is better than thousand words.

Even when the `Artwork#byline` is set to `null` the space reserved for it remains in place. One possible improvement would be centering the `title` vertically when the `byline` is not available.

**Comment by strievi** [comment]
While the initial issue is fixed, this is causing an [unwanted overlap](https://user-images.githubusercontent.com/43119811/83942995-d1b13100-a7f8-11ea-84b7-e9cb6a221f28.png) between `attribution` and `byline` if `title` is `null` or set to an empty string.

**Comment by ianhanniballake** [comment]
Good catch @strievi, we've fixed that issue in #663.
