### ISSUE TITLE
Setting a thousand of artworks takes a lot of time

### ISSUE THREAD

**Issue by arturdryomov** [romannurik/muzei#623]
The title sounds ridiculous but it is true.

Since [the source I’m working on](https://github.com/ming13/muzei-earth-view) contains a limited set of images I ship a defined set of declarations in JSON. It contains something like 1500 elements. I read this JSON, transform it to `Artwork` objects and call `MuzeiArtProvider#setArtwork`. It works fine but there is a noticeable delay before images actually appear on the UI. It might take almost a minute to do so (on a real device). Timings from an emulator:

Step | Time
-----|------ 
Reading JSON                              | 69 ms
Transforming to `Artwork`          | 23 ms
`MuzeiArtProvider#setArtwork` | 3.514 s
Timeout before images appear   | 16 s

One thing I’ve noticed right away is a ton of such log entries:

```
D/MuzeiArtProvider: Notified for batch change on content://ru.ming13.muzei.earthview/1342
D/MuzeiArtProvider: Notified for batch change on content://ru.ming13.muzei.earthview/1341
D/MuzeiArtProvider: Notified for batch change on content://ru.ming13.muzei.earthview/1340
```

Not sure it is necessary to occupy the thread with logging 1.5 K entries, especially taking into account `Uri#toString` calls. But the real issue is somewhere else and it occupies the majority of time.

**Comment by HYngHwang** [comment]
★☆ Roman Nurik ☆★

◎http://muzei.co

◎A living museum for your Android home screen.

◎Muzei is a live wallpaper that gently refreshes your home screen each day with famous works of art.

**Comment by ianhanniballake** [comment]
We've removed the unconditional logging (it is now tied behind `Log.isLoggable()` with the `MuzeiArtProvider` tag) and Muzei 3.4.0 (currently in alpha) drastically improved the loading logic when it comes to that initial huge set of artworks.

**Comment by arturdryomov** [comment]
Just tried 3.4.0 — the improvement is here, thanks!

However, I’ve increased the artworks count to 2600+ and there is still a visual pause. It’s not as bad as it was though:

Step                                               | Time, ms
--------------------------------|------ 
Reading JSON                              | 126
Transforming to `Artwork`          | 25
`MuzeiArtProvider#setArtwork` | 10061

These numbers are from Google Pixel 3a with Android 10 onboard. Timings were taken from the `onLoadRequested` method. The call was done when I’ve chosen the source in Muzei. Seems like artworks appear when the `setArtwork` is done.

Not sure if it’s possible to optimize this further.
