### ISSUE TITLE
Request: Support for WEBP

### ISSUE THREAD

**Issue by sarsamurmu** [romannurik/muzei#625]
What about natively supporting WEBP as source image? Now WEBP is used everywhere in android, So adding support for WEBP would be a great feature.

**Comment by ianhanniballake** [comment]
Unfortunately, WebP is not supported by RenderScript, the technique used to blur images.

If this ever changes in the framework, we would automatically get support for it. But it would only be Android 11 and higher or whenever it gets added, so probably not something you'd want to rely on.
