### ISSUE TITLE
Feature request: TIF format support

### ISSUE THREAD

**Issue by RaggedyCreature** [romannurik/muzei#635]
I'm sorry if this is the wrong place to ask this but will there be any plans to implement .TIF support?

**Comment by ianhanniballake** [comment]
Muzei relies on the [image formats supported by Android](https://developer.android.com/guide/topics/media/media-formats#image-formats), which unfortunately does not include TIF files.

**Comment by RaggedyCreature** [comment]
That's unfortunate, thanks for the reply.
