### ISSUE TITLE
Muzei wallpaper don't work on Lockscreen in MIUI 10

### ISSUE THREAD

**Issue by uzervlad** [romannurik/muzei#636]

**Comment by ianhanniballake** [comment]
Xiaomi purposefully strips out the ability for live wallpapers, such as Muzei, from being on the lockscreen, despite that being the default behavior they get for free with Android.

Please contact Xiaomi to tell them that you'd like them to re-enable the use of live wallpapers on the lock screen. Unfortunately, there doesn't seem to be any workaround besides using a phone from a different manufacturer.
