### ISSUE TITLE
Android 10 update breaks "double-tap to change artwork" functon

### ISSUE THREAD

**Issue by sawe871** [romannurik/muzei#646]
I just updated to android 10 on a Samsung Galaxy s10e. Immediately after the update, the double tap gesture I was using to change backgrounds stopped working.

Using muezi 3.0.2 from f-droid

**Comment by sawe871** [comment]
Did some testing with several launchers, and it seems to be a problem with the Samsung One UI Home.

**Comment by ianhanniballake** [comment]
The Double Tap gesture relies on the launcher implementing the `COMMAND_TAP` API. If Muzei's double tap works in third party launchers such as Action Launcher or Nova Launcher, then you should contact Samsung to have them fix their launcher.
