### ISSUE TITLE
Muzei periodically deactivates on Android 10

### ISSUE THREAD

**Issue by iamvukasin** [romannurik/muzei#654]
As the title says, I have to reactivate Muzei every few days to make it work. After activation, it works fine, changes wallpapers regularly and then stops working. 

I'm using Muzei 3.4.0 Alpha 1 on Pixel 2 XL (Android 10).

**Comment by ianhanniballake** [comment]
Can you contact us at support@muzei.co? We'd really need you to [take a bug report](https://tamingthedroid.com/power-menu-bug-reports) immediately after your wallpaper resets to figure out why your wallpaper is reverting back to the default wallpaper.

Let's move this to email.
