### ISSUE TITLE
Muzei 3.3.0 cannot be used on Android R

### ISSUE THREAD

**Issue by yellowbluesky** [romannurik/muzei#656]
Device is a fresh emulator running the latest Android R preview, downloaded and installed using the AVD.

Muzei 3.3.0 is installed, the apk was downloaded from APKMirror, and I am not signed into Google services.

When I press "ACTIVATE", nothing is observed to happen, and this is printed to logcat:

```
CHANGE_LIVE_WALLPAPER: Not a live wallpaper: ComponentInfo{net.nurik.roman.muzei/com.google.android.apps.muzei.MuzeiWallpaperService}
```

Muzei doesn't freeze; the starry night background continues to animate, and "ACTIVATE" can continue to be pressed.

**Comment by ianhanniballake** [comment]
Yeah, live wallpapers are broken on the current Android R Dev preview. Since I work at Google, I can confirm that Muzei works fine on a future version of Android R. :-)
