### ISSUE TITLE
Daily artwork not updating anymore

### ISSUE THREAD

**Issue by dynobo** [romannurik/muzei#661]
Dear developer,

I'm using muzei happily for over a year now. But since a few weeks, I don't receive new artworks anymore.

Maybe the last update of muzei (I did it 4 weeks ago) broke it? At least I'm not aware of any other related changes/updates...

Muzei v3.2.0
LineageOS 16

Pls let me know if I can support with further diagnosis/support.

Best regards & thanks for the App! :)

**Comment by ianhanniballake** [comment]
Muzei's current production version is Muzei 3.3.0, which became available on October 27th, 2019. The [open beta](https://play.google.com/apps/testing/net.nurik.roman.muzei) has Muzei 3.4.0-alpha01 right now (which came out on April 18th, 2020).

Muzei 3.2.0 is years out of date at this point and has many known issues. I'd strongly recommend upgrading (preferably to Muzei 3.4.0, which also fixes a number of issues with Muzei 3.3.0). If you're still having issues after upgrading, please contact us at support@muzei.co and we can take it from there.

**Comment by dynobo** [comment]
Thanks for the info, but this raises an additional questions: 

I'm using the muzei version from F-Droid, where the newest version in 3.2.0 which have been published on 2020-04-21:
https://f-droid.org/en/packages/net.nurik.roman.muzei/

**Comment by ianhanniballake** [comment]
F-Droid has never been a supported place to download Muzei as per #601, #369, and #204 as F-Droid's [Inclusion Policy](https://f-droid.org/docs/Inclusion_Policy) precludes Muzei from being published there without serious, invasive modifications, which F-Droid seems to have taken upon themselves to do.

You should download Muzei from the Google Play Store.

**Comment by protist** [comment]
FWIW in the F-Droid version, artwork doesn't update automatically for me either. In my case, I had version 3.4.3 installed from F-Droid. Oddly enough, the same version installed from Google Play works fine.

Presumably one of the modifications mentioned by @ianhanniballake is breaking this functionality, but perhaps there should be a note in the F-Droid page informing users that it is unsupported. It took me several days of troubleshooting before I found this GitHub issue page(s).

**Comment by ianhanniballake** [comment]
We don't interact with maintainers of the F-Droid build; you'd need to talk to them to either fix the issue or to have them add a note that the build they have released is broken.

**Comment by protist** [comment]
Thanks for the response. I don't really know what's going on with the politics of the Muzei project, and TBH I'm not really keen to delve in too much. I just posted here in an attempt to help the project and potential users.

Also, FWIW the [Muzei F-Droid page](https://f-droid.org/en/packages/net.nurik.roman.muzei/) has a link to an "Issue Tracker" page that redirects to this project here.
