### ISSUE TITLE
Crash on 3.4.0 Alpha 2

### ISSUE THREAD

**Issue by alvince** [romannurik/muzei#665]
Updated yesterday.
Crash on select source-tab.

cause by `java.lang.IndexOutOfBoundsException: setSpan(-1 ... 5) starts before 0`  

while inflate xml `choose_provider_fragment` on AutoAdvanceFragment#onViewCreated

**Comment by ianhanniballake** [comment]
Yep, upgrade to Muzei 3.4.0 Alpha 3, which fixes this issue.

**Comment by alvince** [comment]
> Yep, upgrade to Muzei 3.4.0 Alpha 3, which fixes this issue.

Thx, I found it and then close this issue just now
