### ISSUE TITLE
Truncated strings in sliders

### ISSUE THREAD

**Issue by strievi** [romannurik/muzei#667]
Caused by localized strings. ['ASSOMBRIR' becomes 'BRIR', 'FLOU' gets slightly cut](https://user-images.githubusercontent.com/43119811/85749606-4812c600-b709-11ea-9533-598e518f6d86.png). Maybe use icons instead?

**Comment by ianhanniballake** [comment]
Thanks for pointing this out! We've fixed the titles so that they are never truncated, no matter which of the strings are the longest.
