### ISSUE TITLE
Triple tap to go to next (local) wallpaper works but not double tap

### ISSUE THREAD

**Issue by GoDzM4TT3O** [romannurik/muzei#671]
If I go under Muzei > Customize Gestures, I see this:

Double Tap
- [ ] Temporarily disable effects
- [x] Next Artwork
- [ ] View Artwork details
- [ ] None

Three Finger Tap
- [ ] Temporarily disable effects
- [x] Next Artwork
- [ ] View Artwork details
- [ ] None

Whenever I double tap on the homescreen, nothing happens but, if I touch the screen with three fingers, I see the next artwork.

Phone: Samsung Galaxy A50
OS: Android 10 (not rooted)
Muzei version: v3.0.2

I'm using the stock One UI 2, not other custom launchers (like Nova launcher)

**Comment by ianhanniballake** [comment]
The Double Tap gesture relies on the launcher implementing the `COMMAND_TAP` API. If Muzei's double tap works in third party launchers such as Action Launcher or Nova Launcher, then you should contact Samsung to have them fix their launcher.

**Comment by GoDzM4TT3O** [comment]
Ah I see, thanks!
