### ISSUE TITLE
'Sources' activity does not dynamically refresh descriptions when system locale changes

### ISSUE THREAD

**Issue by strievi** [romannurik/muzei#675]
This is very minor annoyance but sources `description` won't update when user changes system locale while 'Sources' activity is running.

**How to reproduce** (assuming phone language is English):
 - open 'Sources' activity
 - while activity is running, navigate to system settings and change language to 'French - France'
 - go back to Muzei and check 'My photos'. While `label` is French, `description` is not

Closing and opening the activity again will show the appropriate translations. Seen on Pixel 3a (Android 10) and Nexus 10 (Lollipop).

**Comment by ianhanniballake** [comment]
Thanks for pointing this out. The fix will be available in the next release!
