### ISSUE TITLE
Backdrops no longer working with latest update

### ISSUE THREAD

**Issue by pwd-github** [romannurik/muzei#678]
I'm not sure what changed, but it broke backdrops integration.

**Comment by ianhanniballake** [comment]
Sounds like you should contact Backdrops then, given that every other Muzei source continues to work and Muzei 3.4 is backward compatible with sources using previous versions of Muzei's API.

Installing Backdrops myself, the app doesn't seem to be loading any wallpapers at all at the moment, much less via Muzei.

**Comment by ianhanniballake** [comment]
If no images appear when you tap "Browse" under Backdrops, then the issue is on Backdrops side - it isn't sending any wallpapers to Muzei to display. That would be an issue on their side and you should contact them.

**Comment by megaroeny** [comment]
Yup, they're looking into it. I emailed them on the weekend.
