### ISSUE TITLE
Delay between homescreen and lockscreen effect change?

### ISSUE THREAD

**Issue by fuckkgithub** [romannurik/muzei#685]
I've set my homescreen and lockscreen to have different effects (blur, dim). However, when locking/unlocking there's a 1 sec. - 1.5 sec. delay before the different effects switch and get slowly applied. Is this intentional? If so, there should be the option for an instant switch. 

Using LineageOS 16.

**Comment by ianhanniballake** [comment]
Muzei immediately swaps to the homescreen effects as soon as it receives the broadcast from the system that you've unlocked your device. It should be just as fast as swapping between the Home and Lock screen tabs on the Effects screen in Muzei.

Any other delay in starting that swap is caused by the system itself and not something Muzei can change.

**Comment by fuckkgithub** [comment]
Swapping between the Home and Lock screen tabs on the Effects screen in Muzei still has that 1 sec. - 1.5 sec. delay. Is that usual?

**Comment by ianhanniballake** [comment]
The crossfade duration is set to 750ms (i.e., 3/4ths of a second). That's consistent across Muzei (whether going between effects on the same picture or switching pictures). There should be no delay in starting that crossfade unless there's something seriously wrong with how your device is set up. For example, the blur effect is done via Renderscript, an ultra fast GPU based effect, but if your device is doing it in software, that would be considerably slower.

Are you seeing a delay in the crossfade starting? Or just wanting the crossfade itself to be faster? It would definitely be extremely jarring if that was removed entirely, yes.

**Comment by fuckkgithub** [comment]
The delay is in the crossfade starting. I'll test it out on some other phones and see whether it's consistent.

I've gotten used to it though, the app has just made everything so varied and pretty now. I didn't install it for the longest time because I skimmed half the F-Droid description and assumed you couldn't choose your own wallpapers or refresh period.

**Comment by ianhanniballake** [comment]
> The delay is in the crossfade starting. I'll test it out on some other phones and see whether it's consistent.

I'm not able to reproduce this on any of the devices we have, sorry. Given that, I don't think there's anything we can do on the Muzei side, unfortunately.

> I've gotten used to it though, the app has just made everything so varied and pretty now.

I'm glad you like it!

> I didn't install it for the longest time because I skimmed half the F-Droid description and assumed you couldn't choose your own wallpapers or refresh period.

Note that the **only** supported place to download Muzei is on [Google Play](https://play.google.com/store/apps/details?id=net.nurik.roman.muzei), whose description does clearly indicate that you can choose your own wallpapers, use other sources, and even has screenshots of the Auto Advance settings. The F-Droid version is **not** created or maintained by the Muzei team and is multiple versions behind Google Play (Muzei is on version 3.4.1, not 3.2.0) and is therefore over a year out of date. I'd strongly suggest downloading the official version of Muzei.
