### ISSUE TITLE
Inverted zoom effect on Android 11/Pixel launcher

### ISSUE THREAD

**Issue by strievi** [romannurik/muzei#691]
More specifically, it will zoom _in_ while it should zoom [_out_](https://9to5google.com/2020/06/10/android-11-beta-1-zooms-your-wallpaper-when-you-access-notifications/). Also, **20%** feels [excessive](https://www.reddit.com/r/GooglePixel/comments/ip5yif/comment/g4ifsqe).

**Comment by ianhanniballake** [comment]
You're absolutely right. Note that switching to a zoom out, the default view you'll see in Muzei now is a slightly (10%) zoomed in version of the image that zooms out to full size when you pull down the notification shade.

This obviously only affects Android 11+ devices - other devices will always see the fully zoomed out image.

**Comment by strievi** [comment]
Looks way better now. Yet, I've noticed that only the main screen of the app displays the _zoomed out_ version (i.e., navigating to 'Sources' or 'Effects' will transition to the _zoomed in_ version). Is it expected?

Also, I'm seeing random wobbles or _zoom in_ effects when unlocking from the fingerprint. Not sure if related or even caused by Muzei.

**Comment by strievi** [comment]
Another thing I've noticed is that Muzei's images are aligned left when zoomed.

**Comment by ianhanniballake** [comment]
> Looks way better now, yet I've noticed that only the main screen of the app displays the zoomed out version (i.e., navigating to 'Sources' or 'Effects' will transition to the zoomed in version). Is it expected?

Yes, the main screen (the Art Detail) screen zooms you out to see the full image, that is expected. This is the same mechanism that disables blurring when on the Art Detail screen.

> Also, I'm seeing random wobbles or zoom in effects when unlocking from the fingerprint. Not sure if related or even caused by Muzei.

If Muzei's activity is not open, then the only thing that is changing the zoom is the signal from the system.

> Another thing I've noticed is that Muzei's images are aligned left when zoomed.

Muzei zooms towards the middle of the image. Where the middle of the image is compared to your screen depends on what space your launcher provides to Muzei. Pixel Launcher, for example, always gives live wallpapers more horizontal space even if you only have one home screen. Other launchers, such as Nova Launcher and Action Launcher, have a specific setting for disabling wallpaper scrolling and always centering the wallpaper in the screen. In those cases, you'd always see the zoom being towards the middle of the screen.

**Comment by strievi** [comment]
> Yes, the main screen (the Art Detail) screen zooms you out to see the full image, that is expected. This is the same mechanism that disables blurring when on the Art Detail screen.

That makes sense. I was asking this because I would rather have no transitions between screens, but it's all subjective.

Anyway, thanks for the valuable feedback.
