### ISSUE TITLE
Fix position wallpaper from muzei

### ISSUE THREAD

**Issue by GlitchYou** [romannurik/muzei#698]
I don't use the many tabs to scroll the wallpaper, so if you can add an option to fix the image by the muzei itself or create a control to change the position of the wallpaper along with the blur, brightness and color. I would be very grateful.

**Comment by ianhanniballake** [comment]
We've covered this request previously in #13, #62, #64, #594, #695, and #697. Muzei doesn't control the position of the wallpaper - that is the launcher's responsibility.
