### ISSUE TITLE
Galaxy S20 double tap doesn't work

### ISSUE THREAD

**Issue by megaroeny** [romannurik/muzei#699]
Hello!

I'm on a Galaxy S20 with OS 10.0. I'm trying to do the double tap to remove the effects on my home screen, but the gesture /double tapping action doesn't do anything. 

I know this used to work on my Pixel when I had one. Not totally sure if this is Galaxy dependent.

**Comment by ianhanniballake** [comment]
If it works in third party launchers such as Nova Launcher or Action Launcher, then the problem is with Samsung's launcher.

See #671 for more details.

**Comment by megaroeny** [comment]
@ianhanniballake oh wow okay. Thanks. Any idea what it specifically might be?

**Comment by ianhanniballake** [comment]
Quoting from the other issue:

> The Double Tap gesture relies on the launcher implementing the `COMMAND_TAP` API. If Muzei's double tap works in third party launchers such as Action Launcher or Nova Launcher, then you should contact Samsung to have them fix their launcher.

**Comment by megaroeny** [comment]
> Quoting from the other issue:
> 
> > The Double Tap gesture relies on the launcher implementing the `COMMAND_TAP` API. If Muzei's double tap works in third party launchers such as Action Launcher or Nova Launcher, then you should contact Samsung to have them fix their launcher.

Oops! Sorry, doing too many things, and missed that. Thanks!
